### ISSUE TITLE
雄异不能回血

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#103]
![image](https://cloud.githubusercontent.com/assets/7959436/3666600/2e5b3b18-11f4-11e4-932e-6d117e35436c.png)
0.5.1
by 姜维顶多值五毛

**Comment by Fsu0413** [comment]
雄异改了实现方法……不知道修没修

**Comment by ainomelody** [comment]
![Image](http://imgsrc.baidu.com/forum/pic/item/eec39f13b07eca805244cbab932397dda044830f.jpg)
0.6.0
by 姜维顶多值五毛

**Comment by ainomelody** [comment]
不正常回血
场上有单蜀和以后已知的暗蜀，马腾回血。就是马腾雄异的时候场上只有一个蜀但回血。是不是暗将AI也算上了
![Image](http://imgsrc.baidu.com/forum/w%3D580/sign=383b57d0c9ef76093c0b99971edca301/932e12178a82b9017e5f907e718da9773b12efdb.jpg)
0.6.0
by kevin1559

**Comment by Fsu0413** [comment]
雄异072改了实现方法，不知是否解决…………

**Comment by Fsu0413** [comment]
至今没出过回血问题，close，如果有问题再开
