### ISSUE TITLE
英魂AI有问题么？

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#105]
![image](https://cloud.githubusercontent.com/assets/7959436/3666678/58feddce-11f5-11e4-8acd-969123e2947d.png)
0.5.1

**Comment by Fsu0413** [comment]
英魂真的不知道为何AI从来都不选

**Comment by YanGuam** [comment]
speak和加断点监测一下流程是不是有问题。。

**Comment by ainomelody** [comment]
0.0前排围观

**Comment by zyun7799** [comment]
之前在basara-ai里强制所有人回合开始亮双将，唯独孙坚不听话暗到死，但是现在不知为何又生效了，现在设置了孙坚在掉到两血时会亮将，亮将后英魂发动就正常了

**Comment by YanGuam** [comment]
...真是寂寞
