### ISSUE TITLE
邓艾不会屯田么

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#106]
暗将/蒋琬＆费祎 明置了武将，主将为 暗将，副将为 蒋琬＆费祎
暗将/蒋琬＆费祎 摸了 2 张牌
暗将/蒋琬＆费祎 装备了 藤甲[2]
暗将/蒋琬＆费祎 使用了 杀[4]，目标是 暗将/邓艾
暗将/邓艾 使用了 闪[J]
暗将/蒋琬＆费祎 发动了“生息”
暗将/蒋琬＆费祎 摸了 2 张牌
暗将/蒋琬＆费祎 弃置了 杀[9], 八卦阵[2]

8人局，ai邓艾回合外失去牌时不发动屯田，整局到死都这样
by dog_p
0.6.0

**Comment by Fsu0413** [comment]
没见过

**Comment by ainomelody** [comment]
![image](https://cloud.githubusercontent.com/assets/7959436/3672589/78c70d9e-1262-11e4-8dad-50ae4d5be6f7.png)
![image](https://cloud.githubusercontent.com/assets/7959436/3672592/831381ce-1262-11e4-8a87-68c1c2654b3f.png)
算是改了？

**Comment by Fsu0413** [comment]
…………这个时期的问题啊……我还以为…………
