### ISSUE TITLE
AI董卓主将亮将策略

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#107]
ai用董卓做主将时的亮将策略问题很大，经常看到没满足横征的发动条件他就主动亮个胖子出来然后可怜的副将就打酱油了。。。
0.6.0
by dog_p

**Comment by Fsu0413** [comment]
@zyun7799 你动过董卓主亮将么

**Comment by zyun7799** [comment]
fixed
