### ISSUE TITLE
AI祝融不烈刃

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#110]
庞统/祝融 摸了 2 张牌
庞统/祝融 发动了“连环”将 藤甲[2] 当成 铁索连环[2] 重铸
庞统/祝融 摸了 1 张牌
庞统/祝融 重铸了 知己知彼[4]
庞统/祝融 摸了 1 张牌
庞统/祝融 使用了 杀[9]，目标是 张辽/荀彧
庞统/祝融 发动了“勇决”庞统/祝融 收回了 杀[9]
庞统/祝融 对 张辽/荀彧 造成了 1 点伤害[无属性]
张辽/荀彧 当前体力为 2 ，体力上限为 3
庞统/祝融 弃置了 顺手牵羊[3], 杀[9]

ai祝融哪怕是弃牌都不会发动烈刃。。。。

0.6.0
by dog_p

**Comment by Fsu0413** [comment]
没见过

**Comment by zyun7799** [comment]
这个在7.2见过，现在又正常了

**Comment by ainomelody** [comment]
神奇
