### ISSUE TITLE
AI开A A死队友

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#114]
曹操父子
1、8人局。
2、曹操\曹丕
3、一个A放死两个队友
4、截图：

![image](https://cloud.githubusercontent.com/assets/7959436/3702170/159d3266-13fc-11e4-8912-aa07e061cb6b.png)
![image](https://cloud.githubusercontent.com/assets/7959436/3702179/44a2f280-13fc-11e4-9eb1-1f9fc585963b.png)
0.6.0
by xxyheaven

**Comment by lrl026** [comment]
aoe 问题遇到在调整
