### ISSUE TITLE
横江标记未消失

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#116]
![image](https://cloud.githubusercontent.com/assets/7959436/3702929/b3f30dfc-1404-11e4-9e3c-562601ac5b8c.png)
贾诩回合内伤害了臧霸夏侯惇，但回合过了后横标记没有消失依然存在
0.6.0
by oldyounges
实测没碰到

**Comment by BeginnerSlob** [comment]
确实存在，但是在下回合开始时自动清除，即无BUG。

**Comment by Fsu0413** [comment]
……臧霸被断肠了，没有横江了

**Comment by BeginnerSlob** [comment]
手牌上限-1是后续效果- -所以标记在

**Comment by Fsu0413** [comment]
我知道……
