### ISSUE TITLE
当AI甄姬、蒋费遭遇二张

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#117]
ai甄姬对于敌二张在场时会放弃洛神，而ai蒋费对于敌二张在场却不断生息。而且能不能改善一下ai暂时盟友的情况下还是配合一下二张呢？
![Image](http://imgsrc.baidu.com/forum/pic/item/abd19d8fa0ec08fad29e62eb5bee3d6d54fbda36.jpg)
0.6.0
by oldyounges

**Comment by Fsu0413** [comment]
生息…………return true

**Comment by zyun7799** [comment]
fixed
