### ISSUE TITLE
双雄对象选择AI

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#121]
八人局

颜良＆文丑/贾诩 发动了“双雄”将 闪[8] 当成 决斗[8] 使用，目标是 曹丕/荀彧
曹丕/荀彧 打出了 杀[7]
曹丕/荀彧 对 颜良＆文丑/贾诩 造成了 1 点伤害[无属性]
颜良＆文丑/贾诩 当前体力为 1 ，体力上限为 3
颜良＆文丑/贾诩 发动了“双雄”将 闪[2] 当成 决斗[2] 使用，目标是 曹丕/荀彧
曹丕/荀彧 打出了 杀[8]
曹丕/荀彧 对 颜良＆文丑/贾诩 造成了 1 点伤害[无属性]
颜良＆文丑/贾诩 当前体力为 0 ，体力上限为 3
颜良＆文丑/贾诩 的“完杀”被触发，只能 颜良＆文丑/贾诩 自救
颜良＆文丑/贾诩 向 颜良＆文丑/贾诩, 曹丕/荀彧, 貂蝉/马腾 求桃，一共需要 1 张【桃】
颜良＆文丑/贾诩 使用了 桃[10]
颜良＆文丑/贾诩 回复了 1 点体力

事实是当时因为双头通过并非决斗的方式秒了好些人，以至于我行殇了一大把牌，放在手牌栏里都换行了，但他还是要不断找我决斗
双头的策略问题，自己没杀的时候别找手牌过多的人决斗吧(´つω・`)
0.6.0
by Apozegm璨

**Comment by zyun7799** [comment]
这个应该是写死在决斗这张卡牌里的。。
