### ISSUE TITLE
挂AK弃杀

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#122]
我暗将隔岸观火，电脑8号位暗将/李典已经亮将，然后7号位突然爆发亮将黄忠/暗将，掏出一把AK，我顿感有好戏看了，只见黄忠杀了一下李典，然后李典掉了一滴血，然后黄忠弃牌了，我勒个去，弃牌一看居然3张杀！

by 紫夜丶星痕
0.6.0

**Comment by zyun7799** [comment]
目测之前更多贴里反映的连弩弃牌都是同一个问题，现在已经没有了
