### ISSUE TITLE
倾城BUG

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#123]
邹氏回合内打主将君刘备，副将暗置的赵云时，赵云触发龙胆
0.6.0
by rgq___1001

**Comment by lrl026** [comment]
这个应该是ai用的吧，人肯定用不了。
最好加个canshowGeneral之类的东西，来让ai判断是否能明置武将发动视为技。

当然，现在也能处理，只是麻烦点

**Comment by BeginnerSlob** [comment]
已经有了吧，Player::disableShow这个方法

**Comment by lrl026** [comment]
现版本人和ai都用不了，可以关了
