### ISSUE TITLE
用OpenGL进行加速后photo十分模糊- -

### ISSUE THREAD

**Issue by YanGuam** [Mogara/QSanguosha-For-Hegemony#124]
![qq20140727173040](https://cloud.githubusercontent.com/assets/3531837/3713610/80a3080c-1577-11e4-8c12-77b6d964ffac.jpg)
The item in the first picture is painted by Qt native GUI module
The following pictures show the graphics painted by underlying OpenGL module.
The one below has the same quality with that painted by native module.
![qq20140727170140](https://cloud.githubusercontent.com/assets/3531837/3713609/80a29886-1577-11e4-9860-1acf5103ec6a.jpg)
But this one is extremely blur
![qq20140727170128](https://cloud.githubusercontent.com/assets/3531837/3713619/1afdee1c-1578-11e4-9454-fa31902f4539.jpg)

I'll ask experts in qt-project.org for help tonight, so save the pictures here. 
DO NOT DELETE THEM.

**Comment by Fsu0413** [comment]
为何wontfix…………

**Comment by YanGuam** [comment]
= = 短期无法解决

**Comment by Fsu0413** [comment]
………………
