### ISSUE TITLE
AI丁奉奋迅后直接过

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#126]
发动“给我拉过来”，但是没有出杀或者顺手，也就是说这个的浪费一牌的没用的行为
8人局，丁奉
http://pan.baidu.com/s/1qWpWH2G

0.6.0
by wangdl_100a

**Comment by lrl026** [comment]
@319e38dab03e8c9e8e41c5bccc642f46f9efcf90
