### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#127]
![Image](http://imgsrc.baidu.com/forum/pic/item/7127ecfe9925bc31dcf885d45cdf8db1ca137023.jpg)
![Image](http://imgsrc.baidu.com/forum/pic/item/7dedb40e7bec54e7687b9652bb389b504ec26a3d.jpg)
0.6.0
by 飞雪解说

**Comment by Fsu0413** [comment]
观星我实际操作多次没问题，而且除了他没见过别人反馈观星的问题
