### ISSUE TITLE
马岱潜袭自己人

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#128]
8人局
马岱潜袭本方武将。下家是鲁肃
![Image](http://imgsrc.baidu.com/forum/w%3D580/sign=847901b4a586c91708035231f93c70c6/aaf667600c338744fa4bca30530fd9f9d52aa0c6.jpg)

0.6.0
by 无敌小棒子

**Comment by zyun7799** [comment]
按照现在的ai来看不可能。。除非敌友判断错误
