### ISSUE TITLE
AI牌多不用直接弃

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#129]
卧龙诸葛亮/赵云 明置了武将，主将为 卧龙诸葛亮，副将为 赵云
卧龙诸葛亮/赵云 的武将牌上有单独的阴阳鱼，可以摸一张牌
卧龙诸葛亮/赵云 摸了 1 张牌
卧龙诸葛亮/赵云 摸了 2 张牌
卧龙诸葛亮/赵云 弃置了 闪[J], 贯石斧[5], 杀[Q], 吴六剑[6], 火攻[2], 过河拆桥[Q], 杀[8], 杀[8]
刚才还有一局曹丕张辽也是这样。。AI是牌一多就不会处理要丢麽？

0.6.0
by 冰soul_灰

**Comment by ainomelody** [comment]
虽然是AI的问题还是发了吧，张辽突袭了田丰后田丰技能拆了他的太平要术，然后他吓得直接跳过出牌阶段，扔了好多桃……
![Image](http://imgsrc.baidu.com/forum/pic/item/ba1f77899e510fb339df05dadb33c895d3430c8e.jpg)
0.6.0
by ft2182910

**Comment by lrl026** [comment]
这没服务器信息，无从查起
