### ISSUE TITLE
AI不巧变

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#130]
八人局
张和甄姬不会使用巧变四
![Image](http://imgsrc.baidu.com/forum/w%3D580/sign=2f461d3bf01fbe091c5ec31c5b610c30/f810711ed21b0ef44f58ba13dfc451da80cb3e18.jpg)

0.6.0
by 25263526

**Comment by Fsu0413** [comment]
巧变4已修
