### ISSUE TITLE
AI甘宁拆吕蒙藤甲

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#131]
这算不算正常策略?
![Image](http://imgsrc.baidu.com/forum/pic/item/ef0c9082d158ccbf8996db771bd8bc3eb03541a3.jpg)
![image](https://cloud.githubusercontent.com/assets/7959436/3717047/c5e95112-161e-11e4-85a6-7cfcce9b66a9.png)
0.6.0
by 吾乃天命之子5

**Comment by Fsu0413** [comment]
版本未知不处理。
