### ISSUE TITLE
弱小势力的联合问题

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#133]
打了一个早上，有一个结论，剩下4人，两人是同势力，其余两人不同势力，弱小势力理应联合起来对抗，但经常都是有机会收人头，就只顾收人头，独力对抗同势力的两人。
0.6.0
by 吾乃天命之子5

**Comment by lrl026** [comment]
这个是很早就遗留下来的问题，原来我以为杀死人可以摸3张
