### ISSUE TITLE
邹氏不翻周泰

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#137]
邹氏的最大作用果然还是翻周泰了，他居然翻了……
![Image](http://imgsrc.baidu.com/forum/pic/item/9f1ccffdfc0392459baac3418594a4c27c1e25b6.jpg)
by ft2182910
Apozegm璨: 也不是一直反...就我个人经验来说似乎是翻对一次——翻错一次——翻对一次——这样的循环......

**Comment by zyun7799** [comment]
经查已修

**Comment by Fsu0413** [comment]
老bug了……我修了好几遍才修好
