### ISSUE TITLE
邓艾司马鬼才他人判定后不能屯田

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#139]
上家袁绍发动乱击，五号位夏侯刚烈红桃，我邓艾/司马改判后发动屯田，但右侧显示发动屯田后，没有出判定牌进行屯田
![Image](http://imgsrc.baidu.com/forum/pic/item/2a14abefce1b9d164fb1dc2ff1deb48f8d546458.jpg)
by 晓岚夕雾
百年东风: 司马懿主将，邓艾副将，在对甄姬的洛神进行改判时也是不能屯田

**Comment by BeginnerSlob** [comment]
无法重现。

**Comment by Fsu0413** [comment]
060发布初期的bug，在改了trigger之后就修了
