### ISSUE TITLE
种种二张

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#141]
1,二张杀上家,上家出方块4闪,然后二张无手牌过,弃牌阶段莫名其妙将那张闪固政到自己手牌中了.
2二张可以固政自己.
3二张可以直谏自己
4二张可以固政替换原有装备.
by 暴走漫画人

**Comment by BeginnerSlob** [comment]
fixed

**Comment by Fsu0413** [comment]
确切的说固政有过问题，直谏的问题到现在我们还没查出来
