### ISSUE TITLE
在出闪的时候预亮技能   视为放弃出闪

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#146]
当时我错过了流离的时机，然后再预亮流离，结果不给我出闪了
060
by 张英orz

**Comment by YanGuam** [comment]
我等这种反馈很久了。。

**Comment by YanGuam** [comment]
我来说说原因和我的解决方案。   Server在等待打出牌的响应结构，结果Client突然发了个其他结构的数据包，解析失败就这样了。
我想设置两大类协议，一种是指令型协议（名字乱起，明白就好），Client可以在任意时刻发送，Server收到后分析为指令型协议，就作为指令交由指令处理系统处理（避免传给等待Client反馈的反馈处理系统）；第二种即反馈型协议，Server只在发送服务端指令后处理这种协议的数据包，现在很常用，不多说了。还有如果收到协议不对的反馈型数据包，应该等待至超时，而不是立即结束监听。总之，需要一个信号过滤器来保证信号正确分发给相应的处理模块。

目前托管，预亮，聊天等均应使用指令型协议。将指令型协议分离开来可以保证不会出现发个聊天预亮个武将导致终止询问的问题，是对反馈型协议的保护。此外，客户端指令协议的应用前景也很广阔，方便玩家进行个性化即时联机设置，比如以此发展类似换肤的SP替换系统，即时更换泡泡框和头像等等。

**Comment by takashiro** [comment]
目前服务器处理来自客户端的数据包确实是线性的，应付不了这个问题╮(╯_╰)╭
先理解一下啦啦的方案——就是说，一是要把现在notification的数据包独立处理，一是request的数据包发送后要等待至接收到对应的reply数据包或超时，忽略错误的reply型数据包吧？反馈型的各类数据包之间也应该相互独立。

**Comment by YanGuam** [comment]
是。毕竟高城，言简意赅:+1:

**Comment by BeginnerSlob** [comment]
= =毕竟高城，太了不起了

**Comment by takashiro** [comment]
fixed...0.0....虽然通信协议还得继续改
