### ISSUE TITLE
君主场AI身份判断

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#150]
刘禅在蜀国的情况下放权给魏了，AI没考虑君主刘备第五个依然是野心家？
![Image](http://imgsrc.baidu.com/forum/pic/item/9f1ccffdfc0392455c5c0ebe8594a4c27f1e25ec.jpg)
0.6.0
by ft2182910

**Comment by lrl026** [comment]
这个是身份判断错误造成的，但是跟君主没关系
