### ISSUE TITLE
决斗无限使用

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#151]
七人局
甄姬/郭嘉
一张决斗一直在手牌，不出去，用了4次，杀死队友之后牌全弃了它还在
![Image](http://imgsrc.baidu.com/forum/pic/item/c050dd58ccbf6c817fe85b5abe3eb13531fa40f3.jpg)
![Image](http://imgsrc.baidu.com/forum/pic/item/65c0bf1bb051f819e6c374f8d8b44aed2c73e7f4.jpg)
0.6.0
by 无敌小棒子

**Comment by BeginnerSlob** [comment]
因为某个原因卡牌了- -

**Comment by YanGuam** [comment]
夏侯氏乱入

**Comment by ainomelody** [comment]
= =

**Comment by Fsu0413** [comment]
072已fix
