### ISSUE TITLE
某段AI调试没去掉？

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#152]
单机的时候总是会自己说出自己装备的防具的名字，如SilverLion或者EightDiagram。。
目测是AI调试信息。。

**Comment by YanGuam** [comment]
+1    今天说了一下午的vine

**Comment by lrl026** [comment]
居然没有删掉。。

**Comment by lrl026** [comment]
@0fdc11528e327e3d725b3b62026547f19f6184dc
