### ISSUE TITLE
标包-蜀

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#154]
- [x] 仁德——交给其他角色手牌
- [x] 武圣——略
- [x] 咆哮——X
- [x] 观星——无消耗
- [x] 空城——无消耗
- [x] 龙胆——略
- [x] 铁骑——无消耗
- [x] 马术——X
- [x] 集智——无消耗
- [x] 奇才——X
- [x] 烈弓——无消耗
- [x] 狂骨——无消耗
- [x] 连环——略
- [x] 涅槃——无消耗
- [x] 火计——略
- [x] 看破——略
- [x] 八阵——X
- [x] 享乐——无消耗
- [x] 放权——跳过出牌阶段
- [x] 祸首——无消耗
- [x] 再起——放弃摸牌（无消耗）
- [x] 巨象——无消耗
- [x] 烈刃——拼点（略）
- [x] 淑慎——无消耗
- [ ] 神智——无消耗？？？？？？？

**Comment by Fsu0413** [comment]
铁骑怎么变成无消耗了

**Comment by Fsu0413** [comment]
神智消耗是弃置所有手牌
