### ISSUE TITLE
大概是新卡牌没有使用AI所以AI出牌就傻掉了？

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#160]
![zgd3yv550ukb 3 _st3rik](https://cloud.githubusercontent.com/assets/1858088/3838018/a4fdffb8-1dfb-11e4-9d00-925fba86ecce.jpg)
![b9 j9h fy u y z d whn5](https://cloud.githubusercontent.com/assets/1858088/3838025/bb7183aa-1dfb-11e4-86a5-9852b0bddd12.jpg)

**Comment by lrl026** [comment]
172a38f58ba724119db3065aea8c4ef1d0fa4735
