### ISSUE TITLE
卡牌

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#162]
如截图所示，徐盛/甘宁用了第一次以逸待劳以后，只弃置1张牌，然后不断无限以逸待劳...不断弃置1张....
![Image](http://imgsrc.baidu.com/forum/pic/item/aad17f8da9773912a79a3bd3fa198618377ae212.jpg)
0.6.0
by 黯夜追风

**Comment by BeginnerSlob** [comment]
看到二张了- -
