### ISSUE TITLE
AI双刃杀空城

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#163]
纪灵/袁绍 (对 刘备/马超) 拼点赢！
纪灵/袁绍 执行了“双刃”的效果，使用了 杀[无色]，目标是 卧龙诸葛亮/诸葛亮
纪灵/袁绍 使用【杀】的目标 卧龙诸葛亮/诸葛亮 被取消

ai纪灵拼点赢了会杀空城诸葛

0.6.0
by 【漆黑之牙】

**Comment by Fsu0413** [comment]
双刃有个typo，打开standard_qun-ai.lua，搜索shuangren-slash，改成shuangren_slash就对了，新版已经修复
