### ISSUE TITLE
毒菜吕蒙AI

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#167]
-文姬有牌就悲歌，且断肠很容易断到技能比较不常用的将，像CC/李典断CC，华陀/田丰断田 丰等等。

-吕蒙总是出杀，并不是敌人残血才出手，且拿到连努以后还会有杀出不乾净弃掉的情况。

0.6.0
by LateWone

**Comment by zyun7799** [comment]
很疑惑在什么情况下不应该悲歌？

**Comment by ainomelody** [comment]
自己比队友更需要保护的时候= =

**Comment by lrl026** [comment]
悲歌收益很明显，怕死不悲歌，简直就是个白板，所以我觉得悲歌不用改
