### ISSUE TITLE
挑衅群雄，弘法杀目标偏移

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#171]
姜维挑衅华佗，华佗发动君张角的弘法出杀。。。可他出杀却没指向姜维，居然指向了我。。。。。
![Image](http://imgsrc.baidu.com/forum/pic/item/906d6081800a19d88475bab231fa828ba71e4660.jpg)
0.6.0
by 河大第三任校长

**Comment by Fsu0413** [comment]
弘法杀整体改了，目前不知道AI会不会有这情况
