### ISSUE TITLE
UI缺陷

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#172]
单击最小化按钮后，点击任务栏还原后，画面卡住，现有已知解决办法，单击还原/最大化按钮。

**Comment by YanGuam** [comment]
Win8.1 x86 VS2013 Qt5.3.1 环境表示正常
给楼主一个悲伤的表情

**Comment by lrl026** [comment]
一样卡住

**Comment by Fsu0413** [comment]
Win8.1 X64 VS2013 Qt5.3.1 环境表示正常
给楼主一个高兴的表情

**Comment by BeginnerSlob** [comment]
卡住的原因是什么？

**Comment by BeginnerSlob** [comment]
我的是WIN7 X64 VS2010 QT4.8.6 RELEASE。。然后就卡了- -

**Comment by lrl026** [comment]
我的是WIN7 X64 VS2010 QT4.8.6 RELEASE。。然后就卡了- -

**Comment by YanGuam** [comment]
如果是qt版本或编译器的原因就好办。。

**Comment by BeginnerSlob** [comment]
那你编译一个Release试试，进入RoomScene游戏开始后，点最小化就会卡。

**Comment by YanGuam** [comment]
Win7 x64 MinGW4.8.2 Qt5.3.1 Debug正常

**Comment by YanGuam** [comment]
目测qt版本的原因

**Comment by BeginnerSlob** [comment]
你用Release试试 - -||||

**Comment by YanGuam** [comment]
@BeginnerSlob 在mainwindow.cpp445行加view->viewport()->update();试试
还是不行就没辙了。

**Comment by BeginnerSlob** [comment]
加了运行就崩溃- -

**Comment by YanGuam** [comment]
repaint解决了吗？

**Comment by BeginnerSlob** [comment]
我去试试

**Comment by BeginnerSlob** [comment]
太神奇了- -奇迹般修好了- -
