### ISSUE TITLE
玩家反映希望看到观星框

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#173]
非诸葛玩家也希望看到卡牌排列的过程- -

**Comment by Fsu0413** [comment]
不可能实现，close。

**Comment by YanGuam** [comment]
实现的前提是完成  #146 并行数据处理机制，另外在线性request-reply结构里要为每次询问附加id做标识，实现大致5步
1.服务器计算得出本次线性通信的id，发送request数据包，包内附加此次线性通信的id
2.客户端记录id，移动一次卡牌后向服务器发送notification协议数据包，包内附加通信id标识
3.服务器验证notification包内id，符合此次线性通信的id就broadcast移动
4.客户端完成观星，发送reply数据包（附带id），销毁本地id，服务器验证或等待超时后销毁服务器当前线性通信的id，完成观星
5.观星询问结束后若因为延时等原因收到的不符合当前线性通信id的数据包全部丢弃，防止影响再次观星。

**Comment by BeginnerSlob** [comment]
LS思路无误

**Comment by Fsu0413** [comment]
其实我认为实现没有必要，即使你知道的对面摆放牌的顺序，也不可能知道是哪张牌，为何花这时间做这无用功

**Comment by BeginnerSlob** [comment]
因为玩家有需求，而且这个要求并不无理

**Comment by Fsu0413** [comment]
但是为此大改服务器架构真的大丈夫？

**Comment by YanGuam** [comment]
都说了服务器架构在国战必改。不然预亮个武将都会结束出闪询问。。
而且通信架构从v1开始就很简陋，没有必须保持现状的理由。

**Comment by YanGuam** [comment]
新架构最好加密数据包，以备不测。

**Comment by Fsu0413** [comment]
好吧…………
