### ISSUE TITLE
君张角弘法响应乱武，杀无目标

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#176]
贾诩乱武，君张角使用发动了弘法，但是没有选择任何人，弃掉天兵就直接下一个人了..
![Image](http://imgsrc.baidu.com/forum/pic/item/273e58e736d12f2eb7a290d74dc2d56284356837.jpg)
0.6.0
by 330de日子

**Comment by YanGuam** [comment]
不多谈，那是君张角在弃天兵防止体力流失

**Comment by YanGuam** [comment]
可以加个log说明

**Comment by ainomelody** [comment]
= =

**Comment by ainomelody** [comment]
为毛不杀

**Comment by YanGuam** [comment]
ai问题

**Comment by lrl026** [comment]
974b084e60e3ff2ff27dadfaddf1e1705c1237e1
