### ISSUE TITLE
飞龙后场上出现相同角色

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#178]
bug,使用飞龙夺凤以后。

出现两蒋琬费祎。。。
虽然死了一个，但武器说是从未出现的角色，因此认为是bug。
0.6.0
by virgo哥

**Comment by BeginnerSlob** [comment]
不是BUG，死亡角色武将牌移出游戏

**Comment by Fsu0413** [comment]
其实这个我改过…………我的错，我改回来
