### ISSUE TITLE
AI喜欢为董卓横征创造条件

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#179]
十人国战，剩三魏打一群（董卓），董卓上一位的夏侯渊不断将其打至一血后过，导致其横征了三四次。

也就是缺失 “在无把握杀死或兵粮董卓的情况下避免将其打至一血或空手牌” 的概念。
0.6.0
by 中闪电的小乔

**Comment by zyun7799** [comment]
已在smart-ai的cantbeHurt中增加相关内容
