### ISSUE TITLE
AI急袭无视距离

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#180]
邓艾两个田全牵我了，最后一个无视距离
![Image](http://imgsrc.baidu.com/forum/pic/item/ba1f77899e510fb385efb136db33c895d3430ceb.jpg)
0.6.0
by ft2182910

**Comment by lrl026** [comment]
把"田"当"顺"的时候就不能拿来计算距离了，是这样吗？

**Comment by YanGuam** [comment]
是。

**Comment by BeginnerSlob** [comment]
就是急袭顺，计算的时候fix要+1
