### ISSUE TITLE
AI砍队友

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#181]
10人局
在我（貂蝉/张任）只剩一血的时候，队友（庞德/纪灵）突然给我补了一刀，不明觉厉，而且也没有铁索连着("▔□▔)/
![Image](http://imgsrc.baidu.com/forum/w%3D580/sign=439eaf7f3f6d55fbc5c6762e5d234f40/c3eff4dcd100baa1a818841a4510b912c9fc2ea9.jpg)
0.6.0
by O暗夜公爵O

**Comment by YanGuam** [comment]
这ai一定是虫妹写的。

**Comment by ainomelody** [comment]
机智

**Comment by BeginnerSlob** [comment]
啦啦你再乱说，信不信我砍死你

**Comment by lrl026** [comment]
机智的啦啦，一下子黑了2个人

**Comment by lrl026** [comment]
屎前问题了，已修复
