### ISSUE TITLE
woodenox触发技Triggerable

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-For-Hegemony#186]
不多谈，自己看图片
![qq 20140811003947](https://cloud.githubusercontent.com/assets/4150545/3869878/2d76810e-20ad-11e4-98fe-4f1b0ee5e181.jpg)

![qq20140811003951](https://cloud.githubusercontent.com/assets/4150545/3869873/ffd04f78-20ac-11e4-970c-a10c89c7371d.jpg)

**Comment by Fsu0413** [comment]
@BeginnerSlob 赶紧爬过来看问题- -

**Comment by BeginnerSlob** [comment]
= -你不是说你会修么- -算了，我修完去上班吧

**Comment by Fsu0413** [comment]
我哪里来的那么多时间去修……发现的时候已经快1点了

**Comment by BeginnerSlob** [comment]
你在群里说你来的啊- -

**Comment by Fsu0413** [comment]
我什么时候说过……

**Comment by BeginnerSlob** [comment]
大概凌晨= =

**Comment by Fsu0413** [comment]
我只是说我知道怎么修 ，不过我没说我修……
