### ISSUE TITLE
场上出现同将

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#191]
第一回合，一号位亮刘备，二号位单亮张飞，我拿上连弩杀死左边的张飞，右边又亮出一个张飞，选将上限是7，开了标阵势，没加君主
![Image](http://imgsrc.baidu.com/forum/pic/item/ded056afa40f4bfbf787d6a1014f78f0f53618c5.jpg)
0.6.0
by 任意角的正切

**Comment by ainomelody** [comment]
![Image](http://imgsrc.baidu.com/forum/pic/item/66213687e950352abfa96dfd5143fbf2b0118b49.jpg)

**Comment by ainomelody** [comment]
![Image](http://imgsrc.baidu.com/forum/pic/item/cd5dacec08fa513d6c68272b3f6d55fbb0fbd953.jpg)

**Comment by Fsu0413** [comment]
060不清楚，072肯定有这问题，fixed
