### ISSUE TITLE
AI发动"nil"将【丈八蛇矛】, ***当做【杀】使用

### ISSUE THREAD

**Issue by takashiro** [Mogara/QSanguosha-For-Hegemony#195]
![spear](https://cloud.githubusercontent.com/assets/1375206/3944007/c94e79c4-25df-11e4-81ee-6b40dbf7fa5c.png)

**Comment by BeginnerSlob** [comment]
6666666666666

**Comment by takashiro** [comment]
身为诸葛维【挑衅】的我都要哭泣了

**Comment by BeginnerSlob** [comment]
哈哈哈哈

**Comment by YanGuam** [comment]
:six::six::six::six::six::six::six::six::six::six::six::six::six::six::six:
