### ISSUE TITLE
酒杀不拍明将，搞到己方暗将

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#199]
十人局
AI问题
暗将/华佗 上家是蜀国，下家是我。当时我没亮将 马腾/袁绍，他为何不杀马岱却来酒杀我？？
![Image](http://imgsrc.baidu.com/forum/pic/item/c78243c2d56285356a6968f192ef76c6a5ef63a3.jpg)
by 无敌小棒子

**Comment by BeginnerSlob** [comment]
限制暗将很正常吧？

**Comment by ainomelody** [comment]
确实= =

**Comment by YanGuam** [comment]
上家明将不打，酒杀一个暗将哪里正常了。。

**Comment by ainomelody** [comment]
- -暗将具有改变局势的力量。

**Comment by YanGuam** [comment]
上家具有砍死你的力量

**Comment by lrl026** [comment]
这个肯定是随到2b的ai

**Comment by BeginnerSlob** [comment]
= =限制暗将是一种打法啊。。明将互杀只会被偷取革命果实。

**Comment by YanGuam** [comment]
面对已知的强敌，杀一下暗将可以，酒杀肯定不是好选择

**Comment by lrl026** [comment]
这样吧，不喝酒杀不明身份的暗将
