### ISSUE TITLE
太史拼点赢被断肠后不能使用第二张杀和双杀

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#200]
1、8人局。
2、太史慈。
3、装备连弩，左右卡+1，天义拼点成功，第一张杀杀死蔡文姬，然后不能出杀了。
by 张英orz

**Comment by Fsu0413** [comment]
只是失去技能而已，flag也会失去？

**Comment by lrl026** [comment]
tianyi有EventLoseSkill清flag

**Comment by Fsu0413** [comment]
机智的lrl，我都没发现
