### ISSUE TITLE
实时换肤系统

### ISSUE THREAD

**Issue by YanGuam** [Mogara/QSanguosha-For-Hegemony#204]
- [x] 通信上大致设计是给Player加两个皮肤index属性，客户端发送换肤命令后服务器广播
- [x] UI上可以借鉴tangjs的界面。文件结构上可以建立一个general-skin文件夹，其中的结构为general-skin/zhouyu/1/card.jpg general-skin/zhouyu/1/avatar.png general-skin/zhouyu/1/death.ogg
  general-skin/武将名/皮肤id（从1开始，0代表原插画）/文件名

完成后可以解决#73

**Comment by Fsu0413** [comment]
个人不喜建议有服务器广播的皮肤系统，需要服务器上有皮肤。
还是在自己本地客户端这里自己弄皮肤比较好。否则本来神杀的网络连接就容易掉线，还要传个好几百K的皮肤上去…………

**Comment by takashiro** [comment]
啦啦的意思是不需要服务器传输皮肤，只广播皮肤ID吧。不过考虑到个人偏好相对固定，我也觉得做在本地应该要好一点，可以放在配置选项中。

**Comment by BeginnerSlob** [comment]
= =啦啦的意思肯定是广播ID，然后我的意见和高城一致，可是啦啦不听- -

**Comment by Fsu0413** [comment]
广播皮肤id的话，万一那个客户端没有皮肤不就悲剧

**Comment by YanGuam** [comment]
我想换个sp周瑜保持良好的审美形象，结果别人看到的都还是普通周瑜。
在配置选项中，加个是否同步更换皮肤的选项可破。

**Comment by YanGuam** [comment]
completed.
