### ISSUE TITLE
更改各种dialog的丑陋样式

### ISSUE THREAD

**Issue by YanGuam** [Mogara/QSanguosha-For-Hegemony#206]
改成GraphicsBox的：
- [ ] 选花色的对话框
- [ ] 选势力的对话框
- [x] ChooseGeneralDialog（知己知彼，尚义）

调整样式的：
- [x] ConnectionDialog
- [x] UdpDetectorDialog
- [x] ServerDialog
- [x] ConfigDialog
- [x] FreeChooseDialog
- [x] BanIPDialog
- [x] BanListDialog
- [x] CustomAssignDialog
- [x] CardAssignDialog
- [x] GeneralAssignDialog
- [x] SkillAssignDialog
- [x] GeneralOverview
- [x] GeneralSearch
- [x] CardOverview
- [x] RuleSummaryDialog
- [x] CardEditor
- [x] AboutUsDialog
- [x] DistanceViewDialog
  (ChooseRecordWindow is the system's native dialog. We'd better not adjust it)

待补充

**Comment by Fsu0413** [comment]
话说知己知彼和尚义可以考虑解耦

**Comment by YanGuam** [comment]
耦合了吗？

**Comment by YanGuam** [comment]
ChooseGeneralDialog早就被移除了。

**Comment by Fsu0413** [comment]
…………单独做个函数for knownboth and shangyi，加lua接口

**Comment by YanGuam** [comment]
不干了，主线里全部重写。
