### ISSUE TITLE
悲歌 ai

### ISSUE THREAD

**Issue by lrl026** [Mogara/QSanguosha-For-Hegemony#212]
周泰/蒋钦 使用了 铁索连环[￼K]，目标是 吕布/暗将, 袁绍/纪灵
周泰/蒋钦 使用了 火杀[￼4]，目标是 袁绍/纪灵
周泰/蒋钦 对 袁绍/纪灵 造成了 1 点伤害[火焰属性]
袁绍/纪灵 当前体力为 2 ，体力上限为 4
吕布/暗将 弃置了 桃[￼Q]
吕布/蔡文姬 明置了武将，主将为 吕布，副将为 蔡文姬
袁绍/纪灵 的判定牌为 丈八蛇矛[￼Q]
袁绍/纪灵 的判定结果为 丈八蛇矛[￼Q]
周泰/蒋钦 将武将牌叠置，现在是 叠置状态
吕布/蔡文姬 处于横置状态，将受到传导的属性伤害
吕布/蔡文姬 的防具【藤甲】效果被触发，火焰伤害由 1 点增加至 2 点
周泰/蒋钦 对 吕布/蔡文姬 造成了 2 点伤害[火焰属性]
吕布/蔡文姬 当前体力为 1 ，体力上限为 4
吕布/蔡文姬 弃置了 藤甲[￼2]
吕布/蔡文姬 卸载了 藤甲[￼2]
吕布/蔡文姬 的判定牌为 顺手牵羊[￼3]
吕布/蔡文姬 的判定结果为 顺手牵羊[￼3]
吕布/蔡文姬 摸了 2 张牌

**Comment by Fsu0413** [comment]
没看出来什么问题……

**Comment by Fsu0413** [comment]
…………卧槽，看出来了
