### ISSUE TITLE
删除lua中os.execute函数

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-For-Hegemony#213]

**Comment by lrl026** [comment]
这玩意怎么了

**Comment by Fsu0413** [comment]
@lrl026 主机开作弊的话客户机可以通过在服务器端执行脚本运行这个函数随意控制主机，这样的话主机一定程度上会变成肉鸡

**Comment by Fsu0413** [comment]
removed

**Comment by lrl026** [comment]
这么说的话，应该在服务器上加个选项，屏蔽部分 io，os 函数

**Comment by YanGuam** [comment]
c写的lua里很难获取神杀的用户设置

**Comment by lrl026** [comment]
要不在启用作弊那里加个选项，增加一个选项在服务器执行脚本

**Comment by Fsu0413** [comment]
即使让在服务器里执行脚本的话，也不能让客户端随意调用服务器的程序，这段代码肯定是要删的
