### ISSUE TITLE
玩家希望游戏开始后预留时间允许玩家预亮技能

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#220]
可以考虑加个提示，类似手气卡的，

**Comment by Fsu0413** [comment]
trigger全局gamestart之后，延时3秒开始。如果加提示的话还要加个操作时间的延时，太长了

**Comment by BeginnerSlob** [comment]
= =加个框吧- -这个delay在配置差的电脑上和没有delay没有区别
或者把那个单机自动预亮的设置改成所有游戏自动预亮

**Comment by lrl026** [comment]
要不把那倒计时3秒改到这里，就不会延长太多时间

**Comment by BeginnerSlob** [comment]
= =本来是倒计时3秒，然后选将
强行改了的话就是先选将再倒计时，大丈夫？

**Comment by YanGuam** [comment]
所有游戏自动预亮吧
