### ISSUE TITLE
点开右上角的菜单，若牌局正在进行中，菜单会自动关闭

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#222]
可能和卡牌移动或是log更新有关

**Comment by takashiro** [comment]
#203 中修过装备牌的使用导致菜单缩回的问题。

**Comment by takashiro** [comment]
发现Android下还是没解决。包括#203中发现的装备牌，有多种情况导致菜单关闭

**Comment by takashiro** [comment]
Photo装备区，进度条QProgressBar，武将牌上的牌QPushButton均已修。
还剩下一些现在不会自动show()抢焦点的部分——录像重放控件，聊天窗和游戏记录框等。
