### ISSUE TITLE
AI蒋钦可以空城状态下尚义

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#223]
这个一听就很酷炫- -

**Comment by lrl026** [comment]
没看出shangyiAI有问题。。

**Comment by BeginnerSlob** [comment]
= =可是昨天（还是前天，忘了）的编译版本出现了这个问题- -回头我再看看

**Comment by lrl026** [comment]
![image](https://cloud.githubusercontent.com/assets/3211541/4315349/5b660e54-3ef3-11e4-8b29-6f1cd64717e3.png)
主要部分都没改过，实在看不出有什么问题
