### ISSUE TITLE
transferbutton会引起崩溃

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#225]
重现方式不明，原因不明，概率极高，参见休斯视频

**Comment by lrl026** [comment]
![image](https://cloud.githubusercontent.com/assets/3211541/4591960/78415afa-5074-11e4-957a-df369ee9e93f.png)

**Comment by lrl026** [comment]
![image](https://cloud.githubusercontent.com/assets/3211541/4591981/105bf0a2-5075-11e4-8d36-9525b85f1132.png)

**Comment by lrl026** [comment]
快来拯救一下transferbutton吧
_transferButtons没能正确的移除

**Comment by lrl026** [comment]
貌似不会崩了
