### ISSUE TITLE
替换fmod为QAudioXXX

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-For-Hegemony#226]
基本思路就是在audio.cpp里替换fmodex的引用，同时删掉菜单里的关于fmod

**Comment by takashiro** [comment]
赞啊，几个.h .cpp总比好多个.dll .so方便

**Comment by Fsu0413** [comment]
@takashiro 不过目测……单独用QAudio的话不能放ogg……要link别的库，还不如fmod

**Comment by Fsu0413** [comment]
如果fmod可以静态link就好了，也不用维护dll

**Comment by takashiro** [comment]
fmod不开源嘛，没办法。或许可以考虑换用OggVorbis自己出的libogg和libvorbis，放弃fmod支持的其他格式。不过这样自定义背景音乐那边，支持的格式只能是系统默认可解码的几种格式外加ogg了。

**Comment by Fsu0413** [comment]
现在看来还是fmod好，保持持续更新也不是一件很难的事，就这样吧

**Comment by Fsu0413** [comment]
看看啦啦怎么说 @YanGuam

**Comment by YanGuam** [comment]
暂时还是用fmod吧。。
