### ISSUE TITLE
君刘备在场龙胆无效

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-For-Hegemony#23]
目测按钮重写之后触发技的问题，因为在按钮重写之前技能没有问题。
曾经尝试更改技能，不过以失败告终。

**Comment by Fsu0413** [comment]
就是那些不能预亮的触发技带视为技全部无效

**Comment by YanGuam** [comment]
accepted

**Comment by YanGuam** [comment]
fixed. 3b85e6de2898b168652881ba53364ecef92b2492

**Comment by Fsu0413** [comment]
双雄依旧无效，reopen

**Comment by YanGuam** [comment]
fixed. 4a6599e4900478d79ed7f1ee662ebde00efb5b34
Remove the temp branch.
