### ISSUE TITLE
崩：开始时只选一个武将

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#230]
只选择一个武将，等时间到了，就会崩。只有剑阁会出现这种情况，2-10人局正常。
besides,选了一个和没选一样么= =，主副将都不是选择的那一个。
小场景里选一个，更坑。
![image](https://cloud.githubusercontent.com/assets/7959436/4701017/f8a71b1c-5853-11e4-95ef-6e5fcdef6edc.png)

**Comment by YanGuam** [comment]
无法重现

**Comment by Fsu0413** [comment]
@YanGuam 剑阁

**Comment by YanGuam** [comment]
我这里无法重现，你呢？

**Comment by Fsu0413** [comment]
@YanGuam 重现
