### ISSUE TITLE
选将框武将牌重叠及半空悬停

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#231]
![Image](http://imgsrc.baidu.com/forum/pic/item/d08698eef01f3a2994b193b39a25bc315d607ca0.jpg)

**Comment by ainomelody** [comment]
![image](https://cloud.githubusercontent.com/assets/7959436/4701102/00203922-5855-11e4-990f-cef8738bdebc.png)

**Comment by ainomelody** [comment]
武将牌重叠的时候向下拖就会半空悬停

**Comment by takashiro** [comment]
看样子是QQuickWindow在用很奇怪的方式影响QMainWindow的绘制。

**Comment by Fsu0413** [comment]
什么情况，只能assign一个人么

**Comment by takashiro** [comment]
Quick 2.0和QPainter系混用出的问题太奇怪太多。
lrl大神说的对。感觉我换2.0操之过急了，现在还不是时候。
@Fsu0413  @YanGuam  改回QDeclarative*？

**Comment by lrl026** [comment]
我觉得先把改animation的还原吧，重发个exe
要不现在的版本根本没法玩

**Comment by Fsu0413** [comment]
等等，我感觉应该是缺plugin

**Comment by Fsu0413** [comment]
暂时把lightbox写在cpp里吧，等全部脚本化之后再弄这个也不晚
