### ISSUE TITLE
亮将后托管，潜伏图片会重新出现

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-For-Hegemony#24]
rt

**Comment by Fsu0413** [comment]
还有一层黑色半透明的东西也会出现

**Comment by YanGuam** [comment]
accepted

**Comment by BeginnerSlob** [comment]
部分情况下技能按钮预亮状态和显示状态恰好相反：
重现方法：甄姬主将，夏侯渊副将，夏侯渊处于非预亮状态，
回合开始，出现亮将与预亮选框，此时预亮夏侯渊，然后发动洛神（或展示主将），然后不展示副将，然后BUG重现，神速半透明时，潜伏字样消失，神速不透明时，潜伏字样出现，此时字样显示的为正确状态，即按钮图片与实际情况恰好相反
