### ISSUE TITLE
距离技亮将

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#242]
整体思路：
卡牌增加距离技亮将参数（类TargetModSkill）
Player类新增一个方法询问距离亮将int Player::countingDistanceTo(const Player *other) const  = 0;
在client和server分别重载（其中client无法询问亮将-借刀待修正）

**Comment by BeginnerSlob** [comment]
考虑到太复杂，暂时不考虑动手。

**Comment by YanGuam** [comment]
个人认为应考虑马术亮将问题了。
1.你选择目标时：包括杀（乱武）、顺、兵、潜袭。
若吴魏有马术：强袭、短兵。
2.判断技能发动条件时：目前只有狂骨。
个人认为其他角色选择目标时（借刀）发动马术不合逻辑。
奇才红颜都超越OL了，马术可以吗？
--by zjznj

**Comment by BeginnerSlob** [comment]
马术不可以- -因为有客户端的部分。。
除非和.NET一样把card的targetfilter放到服务端上

**Comment by YanGuam** [comment]
.NET是怎么设计的呢？

**Comment by BeginnerSlob** [comment]
点选卡牌通知服务端，服务端计算卡牌选择的合法性，返回合法目标，客户端点选一个目标后，再传入服务端，以此类推， 直至点击下确定按钮。

**Comment by YanGuam** [comment]
貌似不错啊？   强效防数据包hack，还能和AI系统整合

**Comment by BeginnerSlob** [comment]
但是这样会增加程序的网络访问频率。但是好处是可以防止截包作弊。

**Comment by Fsu0413** [comment]
wontfix关了
