### ISSUE TITLE
方天高亮

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#243]
= =似乎回合武圣之类的高亮冲突，该怎么玩。。。

**Comment by YanGuam** [comment]
为何一定要点方天才能发动技能

**Comment by Fsu0413** [comment]
我也不赞成点方天发动技能……

**Comment by BeginnerSlob** [comment]
1.视为使用杀需要可以发动方天特效。
2.将短兵的额外目标和方天的基本目标做区分。
3.在只杀两名角色的时候，区分方天和(短兵or天义)的区别。
如果能实现上述三点，我同意“不点方天也能发动方天”。@YanGuam @Fsu0413

**Comment by BeginnerSlob** [comment]
哦对- -还要兼顾1&&2

**Comment by Fsu0413** [comment]
我记得虫妹以前跟我说过这个问题，我的想法是把发动方天天义短兵等等的选择放到Slash::onUse()函数里，我也曾经尝试实现过，后来感觉有点问题就没再继续弄，但是总是感觉这个实现有点…………
现在的问题是【杀】牵扯到的结算特别复杂而且很乱……求三国杀官方简化【杀】的结算流程。

**Comment by YanGuam** [comment]
@BeginnerSlob 否则1.需要颠覆现有视为技架构。
2.耦合。

第一点对于人员逐步撤离的版本来说不现实。

**Comment by YanGuam** [comment]
而且耦合也很不好做。   我建议在服务器突破，而不是ui上

**Comment by BeginnerSlob** [comment]
= =你们加油- -除非你们能解决这个方天杀的结算，否则我不同意改方天
