### ISSUE TITLE
桃目标转移，，，

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#244]
![Image](http://imgsrc.baidu.com/forum/pic/item/27190646f21fbe09a1f1e77668600c338644ad73.jpg)

**Comment by ainomelody** [comment]
![Image](http://imgsrc.baidu.com/forum/w%3D580/sign=9905e1786359252da3171d0c049a032c/8cc40524ab18972b94fb03a8e5cd7b899c510ae4.jpg)

**Comment by lrl026** [comment]
fixed
d89894b9e0abfea1d74c9dc6b00c2df3af3a09e3
