### ISSUE TITLE
三尖两刃刀搞自己

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#249]
![Image](http://imgsrc.baidu.com/forum/w%3D580/sign=1df046b43e6d55fbc5c6762e5d234f40/c3eff4dcd100baa1f6766dd14410b912c9fc2e57.jpg)

**Comment by ainomelody** [comment]
![Image](http://imgsrc.baidu.com/forum/w%3D580/sign=6589223756fbb2fb342b581a7f4b2043/a40edd00baa1cd114eec584aba12c8fcc2ce2d57.jpg)

**Comment by ainomelody** [comment]
火杀目标黄月英

**Comment by lrl026** [comment]
原因不明

**Comment by lrl026** [comment]
大概和结婚有关，大概fixed
