### ISSUE TITLE
出现同将

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#250]
![Image](http://imgsrc.baidu.com/forum/pic/item/55259c529822720e43f5519178cb0a46f31fabf0.jpg)司马懿
![Image](http://imgsrc.baidu.com/forum/pic/item/eb974fa98226cffc0e790cd9ba014a90f703ea58.jpg)甄姬

**Comment by YanGuam** [comment]
！

**Comment by ainomelody** [comment]
新版本记录AI选将框

**Comment by YanGuam** [comment]
出现问题再reopen

**Comment by ainomelody** [comment]
。。。。都出现N次了。。。。

**Comment by YanGuam** [comment]
我说在beta3出现问题再说，不知道上面修的有没有用。。
