### ISSUE TITLE
角色阵亡后判定区的牌仍显示在脸上

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#254]

**Comment by YanGuam** [comment]
很不幸，无法重现

**Comment by ainomelody** [comment]
![qq 20141110190620](https://cloud.githubusercontent.com/assets/7959436/4974902/aae6e5a0-690c-11e4-81d3-8fc07f451258.jpg)

当前窗体失去焦点标记就会消失

**Comment by Fsu0413** [comment]
重画的问题？

**Comment by YanGuam** [comment]
出现问题再reopen
