### ISSUE TITLE
远古bug

### ISSUE THREAD

**Issue by lrl026** [Mogara/QSanguosha-For-Hegemony#256]
lua 里 card：getPackage（） 都是返回空串

**Comment by YanGuam** [comment]
看了下，clone的时候不能传递parent 因为parent是在主线程上的，服务器的卡牌在room线程上

解决方案还需讨论研究

**Comment by lrl026** [comment]
那么应该可以用getEngineCard，我去试试

**Comment by YanGuam** [comment]
@lrl026 有用吗

**Comment by lrl026** [comment]
有用
