### ISSUE TITLE
AI 问题汇总

### ISSUE THREAD

**Issue by lrl026** [Mogara/QSanguosha-For-Hegemony#258]
- [x] 1.吕布无双AI出一闪掉血
  【没录像无解】
- [x] 2.黄盖弃牌阶段弃桃子怎么办？
- [x] 3.非群雄的ai在张角(非君主)存活时会去判八卦/八阵
- [x] 4.还有是电脑不会用木牛流马里面的牌，给桃都不吃......
- [x] 5.传了张木牛流马给华佗，里面有红杀红闪，南蛮，华陀啪，用木牛急救
- [x] 6.我是1血华佗，鲁肃好施给我3红牌然后干我。。【没录像无解】
- [x] 7.太史慈不要连横大点数。一次给我了一张K然后跟我天义。
- [x] 8.张辽因貂蝉的离间杀死了曹操，手里有桃不救，却白白丢了四张手牌，这AI也是醉了【没录像无解】
- [x] 9.另外有一次剑阁AI放了个联军盛宴让对面回了3滴血自己才拿4张牌；水淹七军似乎没有考虑武将技能对牌的影响。
- [x] 10.昨天做掉贾诩，暗将华佗，一手红牌，不懂得急救。应该是没有的,我说的条件是华佗暗将.就是说我认为AI没明将不会考虑发动急救. 【没录像无解】
- [x] 11.AI建议：AI姜维刘禅到死没挑衅过，很早就双亮了 
- [x] 12.黄盖不管情况一直苦血自杀是正常的吗? 刚才打了一盘大吴国, 差不多解决最后2个敌人的时候, 黄盖不顾一切连续苦肉自杀… (耗了3桃也不停...) 马上直接崩盘= ="
- [x] 13.AI狂杀有八卦的郭嘉甄姬。。
- [x] 14.二号位 摸了 2 张牌;
  二号位 使用了 知己知彼[3]，目标是 邹氏/庞德;
  二号位 观看了 邹氏/庞德 的 主将;
  二号位 发动了“青囊”弃置了 南蛮入侵[K]，目标是 二号位;
  暗将/华佗 明置了武将，主将为 暗将，副将为 华佗;
  暗将/华佗 回复了 1 点体力;
  暗将/华佗 当前体力为 3 ，体力上限为 3;
  暗将/华佗 使用了 乐不思蜀[6]，目标是 邹氏/庞德;
  暗将/华佗 对 邹氏/庞德 使用延时锦囊 乐不思蜀[6];
- [x] 15.目测联军的无懈判断有问题@lrl026
  ![image](http://imgsrc.baidu.com/forum/w%3D580/sign=66e4865b0fd79123e0e0947c9d355917/2422fb36afc37931a631507ae8c4b74542a9115e.jpg)
- [x] 16.还是放一张图吧，截的有点晚了，当时大乔还没有+1，诸葛手里一把杀全弃了

![image](http://imgsrc.baidu.com/forum/w%3D580/sign=4f2ed88f0bfa513d51aa6cd60d6c554c/3bdbc53d70cf3bc7419c80bfd200baa1cc112a13.jpg)
- [ ] 17.调虎队友然后开以逸待劳

![Image](http://imgsrc.baidu.com/forum/w%3D580/sign=8d75f8995166d0167e199e20a72ad498/50059d2397dda144199a17e6b1b7d0a20df48621.jpg)
- [x] 18.黄忠已被调虎情况下还能成为曹操远交近攻的目标
- [x] 19.任意武将对方一血一拍 ai去顺/拆/反馈他装备【没录像无解】
- [x] 20.暗将明显表现出是某个势力而且加上这个暗将是最大势力 比如是2+1 ai仍然去打嘲讽低的势力（2个蜀国）【没录像无解】
- [x] 21.同势力残雪放AOE导致队友死亡弃牌 敌方状态比较好。【没录像无解】
- [x] 22.
  ![image](https://cloud.githubusercontent.com/assets/7959436/5181995/43b79614-74d7-11e4-922c-2431048bed18.png) 不发动神速坐等弃装备（录像见聊天群群文件）
- [x] 23.

![Image](http://imgsrc.baidu.com/forum/pic/item/0929befb43166d22313470c0452309f79152d271.jpg)CC1V3开联军，对面不无懈CC
- [ ] 24.调整连环

![20141231162149](https://cloud.githubusercontent.com/assets/3211541/5586462/7db1a8c0-9109-11e4-89f2-2fdd0172a628.jpg)
- [ ] 25.南蛮不用国·无懈被踩死

![image](http://imgsrc.baidu.com/forum/w%3D580/sign=e718bcc5a386c91708035231f93c70c6/aaf667600c338744992a7741550fd9f9d62aa076.jpg)

**Comment by lrl026** [comment]
好多啊，争取在明年前弄完

**Comment by Fsu0413** [comment]
无录像不管了吧

**Comment by ainomelody** [comment]
还有我说的那个神速弃木牛，里面一张桃子。神速的AI感觉。。。不能愉快玩耍

**Comment by Fsu0413** [comment]
@ainomelody 木牛ai早就解决了吧

**Comment by BeginnerSlob** [comment]
加一个。
暗将太史慈找明将队友天义，队友出了一个K。（嗯。

**Comment by Fsu0413** [comment]
进度怎样

**Comment by lrl026** [comment]
最近很忙，没时间

**Comment by Fsu0413** [comment]
那就关了，要发版了

**Comment by YanGuam** [comment]
先放着
