### ISSUE TITLE
弘法时点问道，天兵留在手牌中

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#260]
![image](https://cloud.githubusercontent.com/assets/7959436/5023977/81937140-6b3d-11e4-8721-aa2b5a304e66.png)

就算装备了还是那样= =

**Comment by ainomelody** [comment]
使用这些牌不会进入弃牌堆,可以无限使用.

**Comment by Fsu0413** [comment]
bug重现
