### ISSUE TITLE
 把自动保存录像功能改为默认开启？

### ISSUE THREAD

**Issue by lrl026** [Mogara/QSanguosha-For-Hegemony#262]
方便处理各种问题

**Comment by Fsu0413** [comment]
会导致神杀文件夹迅速变大，一个录像好几百k呢

**Comment by takashiro** [comment]
说起录像，我想学一下docx, xlsx这种格式对录像文件压缩。基本能降到几十KB(●´ω｀●)ゞ不过还是避免不了神杀文件夹迅速变大，可能我们需要自动清除老录像了=。=

**Comment by Fsu0413** [comment]
@takashiro docx，xlsx不就是zip么……压缩的话，正好用7z来压…………

**Comment by takashiro** [comment]
对啊，很方便的。做成能读多个文件的压缩包就更小了(●´ω｀●)ゞ

**Comment by YanGuam** [comment]
维护第三方模块总是费劲= =

**Comment by takashiro** [comment]
看啦啦的皮肤包怎么弄了=。=
不用7z的话，录像可以考虑简单地用qCompress和qUncompress来单个文件压缩，仔细一想上面说的固实压缩影响单个文件读取速度，不固实不如单文件压

**Comment by YanGuam** [comment]
皮肤包的设计太复杂了=。=
不知道谁来设计一下。。。

**Comment by YanGuam** [comment]
压单文件吧。 但是我还是不赞成默认开启自动保存录像，除非自动上传至服务器。

**Comment by YanGuam** [comment]
我的想法：
1.录像单文件压缩 
2.beta版录像在得到授权后全部上传至服务器，写个简易的服务端分类接收录像

**Comment by takashiro** [comment]
那这issue就移交主线？收集录像的功能加入收集BUG的服务器端？

**Comment by YanGuam** [comment]
可以先实现压缩的吧？

**Comment by takashiro** [comment]
发现已经有png格式是qCompress压缩的了  0.0

**Comment by YanGuam** [comment]
以png格式保存确实比较奇怪= =     想必没什么人用。。不如把qsgs压缩，在录像文件开始处标注是否经过压缩，然后分情况处理录像，png的奇怪格式就不要再用了。

**Comment by takashiro** [comment]
OK

**Comment by Fsu0413** [comment]
可以开启了么

**Comment by YanGuam** [comment]
新架构附带的崩溃汇报器升级，传崩溃信息和录像。其中测试版默认自动传录像到服务器。
