### ISSUE TITLE
当有技能（如三尖、护援）需要选择角色时，不满足发动条件的角色不会变深（虽然无法选择）。 不过选择后取消选择，就变深了

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#266]

**Comment by YanGuam** [comment]
问题出现在连续askForUseCard后

**Comment by YanGuam** [comment]
应该是第二次询问时，调用effectout后，加黑特效的动画还没结束，导致没有再次加上SentBackEffect，所以第三次询问时又正常了。即连续多次询问，奇数次正常，偶数次不正常。
手动暂停RoomThread，给主线程一定时间，bug消失。
