### ISSUE TITLE
诸葛杀小乔，小乔弹月英，诸葛居然见死不救

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#267]
![Image](http://imgsrc.baidu.com/forum/w%3D580/sign=d3ebb4880bfa513d51aa6cd60d6c554c/3bdbc53d70cf3bc7dd59ecb8d200baa1cc112a5e.jpg)
![Image](http://imgsrc.baidu.com/forum/w%3D580/sign=fb47bf7c942bd40742c7d3f54b889e9c/f1e65582b2b7d0a2fe9725c9c8ef76094a369a5e.jpg)

**Comment by lrl026** [comment]
图没用，要录像

**Comment by Fsu0413** [comment]
图没用，关了
