### ISSUE TITLE
调整飞龙与烈弓发动顺序（即TargetChosen时机的结算）

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#268]

**Comment by Fsu0413** [comment]
原因：烈弓对每名角色进行结算时，时机为TargetChosen，player为该角色
飞龙结算时，时机同样为TargetChosen，player为拥有飞龙的人

所以标题应为调整TargetChosen时机所有技能的结算

**Comment by Fsu0413** [comment]
按理来讲这个问题在加入了TargetChoosing/TargetChosen时机之后就有了啊，为什么0.7.2没人反馈这个

**Comment by BeginnerSlob** [comment]
。。。其实现在的结算确实有这个问题。。。
举例来说明。

场上按照座次 武将A 烈弓铁骑，武将B 技能X（一名角色指定【杀】的目标后，你可以令该角色摸一），武将A发动方天杀CDEFGHI
现在程序的结算是，先发动X，然后对每名角色询问烈弓+铁骑。
正确结算是，先对CDEFGHI各询问一次烈弓+铁骑，然后轮到B的时候询问X。

总之现在的触发机制还不够完善。

**Comment by BeginnerSlob** [comment]
期望的解决办法是对触发技加入Target参数，这样可以同步解决多角色颂威+暴虐等问题。

**Comment by Fsu0413** [comment]
萌货…………

**Comment by BeginnerSlob** [comment]
孟获？

**Comment by Fsu0413** [comment]
嗯

**Comment by BeginnerSlob** [comment]
萌货怎么了，没懂。

**Comment by Fsu0413** [comment]
比如A拥有两个技能：
技能1：每当你使用一张锦囊牌指定一名角色为目标后，你可以摸一张牌。
技能2：每当你使用一张锦囊牌指定一名角色为目标后，你可以回复1点体力。
现在A B 萌货 C D E F坐在一起
A回合放南蛮，按理来说应该是对B 萌货 C D E F分别技能1212121212，然后轮到萌货在对B结算时祸首
现在的结算是：A回合放南蛮，对B发动12后萌货祸首，再对孟获CDEF发动12121212，就像你在楼上说的那样

**Comment by BeginnerSlob** [comment]
于是现在找到了颂威暴虐的解决办法。但是随着铁烈结算的修改。出现了新的不可预期的问题。
