### ISSUE TITLE
AI黄月英兵远位不亮将

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#269]

**Comment by Fsu0413** [comment]
今天的修复可能会起作用……等下个版本看看有没有人反馈吧，没人反馈的话正式版就关了

**Comment by YanGuam** [comment]
@QSanguosha/test-team 把ai-selector/general-value.txt里的huangyueying后面的数字改成100，然后在游戏中注意观察ai使用月英是否有楼上提及的bug
要求观察ai月英对距离1以上角色使用兵粮10次以上。

**Comment by YanGuam** [comment]
1月2日的源码版本问题重现
![qq 20150106161112](https://cloud.githubusercontent.com/assets/3531837/5625896/adf74bf2-95be-11e4-97bf-455c8e86d768.jpg)
![qq 20150106161120](https://cloud.githubusercontent.com/assets/3531837/5625897/ae00423e-95be-11e4-860b-9c9e125cef02.jpg)

**Comment by YanGuam** [comment]
@MogaraOrg/test-team 测试任务取消

**Comment by YanGuam** [comment]
@MogaraOrg/test-team 继续测试吧。。。    每遇到一局传一个录像，总共10次就行了。。如果中途bug了，反馈一下，然后中断测试。

**Comment by Fsu0413** [comment]
好像最近好了……大家发现没有
