### ISSUE TITLE
录像回放中技能预亮后潜伏没去掉

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#272]
![qq 20141125194120](https://cloud.githubusercontent.com/assets/7959436/5182292/5442bcbc-74db-11e4-9db8-fa37fd5267a2.jpg)

**Comment by YanGuam** [comment]
方案一：回放时禁止点按钮
方案二：服务器更新客户端的预亮状态，写入录像文件
方案三：客户端hack，直接写入录像文件

方案二三专为秀操作而准备。

**Comment by ainomelody** [comment]
。。。。。回放时没点技能按钮。。。。。

**Comment by takashiro** [comment]
想起选将和观星步骤。
不是“预亮后潜伏没去掉”，而是预亮操作根本不记录在录像里。
准备构思一下主分支改录像这块——Replayer控制界面上的按钮，秀操作= =|||

**Comment by ainomelody** [comment]
不对啊。。。按钮颜色变了，我没动它。。。

**Comment by takashiro** [comment]
。。。真的不是因为技能发动了或者亮将了才变的吗。。。

**Comment by ainomelody** [comment]
应该是玩家预亮了技能，被记录在录像中

**Comment by takashiro** [comment]
=。=求录像

**Comment by ainomelody** [comment]
聊天群群文件里。。。dalong传的

**Comment by takashiro** [comment]
那个是发动【突袭】亮了张辽更新一下技能预亮状态，不是玩家点【奸雄】预亮的时间。
不然手速也是相当快╰(￣▽￣)╮

**Comment by YanGuam** [comment]
@takashiro 没理解   你看看吧

**Comment by takashiro** [comment]
@YanGuam   我0.0只是设想一下主分支未来的录像功能0.0
