### ISSUE TITLE
小乔对贾诩使用黑桃（红颜）兵粮寸断，会被贾诩取消

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-For-Hegemony#276]
经查问题出现在Room::updateCardsOnGet()函数中。
此问题如果想修复的话，需要更改此函数，不过因为所有卡牌移动过程都走的这个函数，可能影响到所有的卡牌移动，尤其是与判定区相关的卡牌移动影响最大。

**Comment by Fsu0413** [comment]
lrl的建议是先改掉然后出问题再说，不过我不想改这部分，对程序影响太大，所以我想问问大家的意见。

**Comment by lrl026** [comment]
这个只是影响客户端显示吧？

**Comment by lrl026** [comment]
还有黑桃的铁锁，这个问题有点麻烦啊

**Comment by Fsu0413** [comment]
不清楚，我 现在暂时没时间改，等有空再说吧

**Comment by BeginnerSlob** [comment]
黑桃的铁索没问题。。。
乐是因为官方萨比规定：延时锦囊进入判定区后花色复原。

**Comment by Fsu0413** [comment]
wontfix……萨比设定
