### ISSUE TITLE
巧变被跳过阶段

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-For-Hegemony#277]
参考规则集40页关于巧变和兵粮的说明。
我们是不是应该改改

**Comment by YanGuam** [comment]
求详情

**Comment by Fsu0413** [comment]
bug贴45l

**Comment by YanGuam** [comment]
![](http://imgsrc.baidu.com/forum/w%3D580/sign=447f0b4473cf3bc7e800cde4e101babd/469e5d0fd9f9d72a432fe754d72a2834359bbb06.jpg)
投票吧。。

**Comment by YanGuam** [comment]
我支持改

**Comment by BeginnerSlob** [comment]
巧变从最开始就是单消耗。。当初这么写是为了防止误操作。（我在贴吧原帖的原话）
