### ISSUE TITLE
发动观星排完顺序以后点确定游戏崩溃

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#28]
应该是按键或者box

**Comment by BeginnerSlob** [comment]
同样情况的还有悟心（UpOnly）
恂恂（DownOnly）则没有问题

**Comment by YanGuam** [comment]
accepted

**Comment by Fsu0413** [comment]
不是UpOnly或者DownOnly的问题，是观星框的clear部分调用了一段不正确的代码导致如果观星之前用过五谷框则没有问题
fixed
