### ISSUE TITLE
AI各种双杀。。。

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#280]
1、座次关系为孙尚香/周瑜（四号位），暗将（六号位，装备了三尖两刃刀），曹丕/徐晃（七号位）。被借刀时暗将同时指定2个目标
![Image](http://imgsrc.baidu.com/forum/w%3D580/sign=eb797f4c2b34349b74066e8df9eb1521/cbf9d80735fae6cdb5dd35370cb30f2443a70f49.jpg)
2、![Image](http://imgsrc.baidu.com/forum/pic/item/cbd83c4e251f95ca89ab51e1ca177f3e66095259.jpg)

**Comment by lrl026** [comment]
已经修复了，应该不会再出现
