### ISSUE TITLE
关于铁烈*3+激昂三技能同时机的TriggerOrder的UI

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#281]
首先说一下结算。
不计激昂的情况下。
铁烈*3的排列组合方式有6!/3!/3!
6!表示6个技能随意排列组合。
两个3!分别代表了一个额外规则。即铁B不能于铁A前被触发（C同理）
即铁AB烈ABC铁C是合法的。
即铁AC烈ABC是合法的。
即铁AC烈ABC铁B是不合法的。
然后激昂可以于以上六个技能前后任意触发。
即7!/3!/3!
楼下简述UI策划

**Comment by BeginnerSlob** [comment]
TriggerOrder中同时显示7个技能的按钮与取消按钮。
如果把鼠标移动到铁A或烈A皆可
若移动到铁B则铁A变暗表示失效
移动到铁C则铁AB变暗表示失效

楼下简述传输接口

**Comment by BeginnerSlob** [comment]
考虑到颂威等用 skillName!sgs1 这样来传输
这里可以用到 skillName!sgs8+sgs1+sgs5 这样
若检测到!且split("+")的length不为1，则传入TriggerOrder时用如下代码
skillName!sgs8&1
skillName!sgs1&2
skillName!sgs5&3
这样来表示
TriggerOrder的UI可以用于检测结尾两位
startsWith“&” && 末位为Number
然后检测!前的所有内容，和末尾的数字，前面吻合且末位数字小于鼠标停留的button，则变暗。

**Comment by Fsu0413** [comment]
太长不看

**Comment by BeginnerSlob** [comment]
好一个太长不看

**Comment by YanGuam** [comment]
= = 我请求先改好传输协议，不然不太好测试

**Comment by BeginnerSlob** [comment]
哦。那我马上改。

**Comment by BeginnerSlob** [comment]
为什么只能关联一个人。。

**Comment by Fsu0413** [comment]
确实只能关联一个人，太诡异了
