### ISSUE TITLE
UI：TriggerOrder非武将技能会被关联上头像

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#283]
如：
崩坏
英姿 英魂
勇决

等。

**Comment by BeginnerSlob** [comment]
解决方案（暂）：（下方括号内的数字代表triggerlist返回值中字符串的类型）
1、武将技能显示武将头像。(1,3)
2、自身技能但非武将技能不显示头像。(1,3)
3、其他角色技能显示技能拥有者主将的头像。(2)

第三条可以改为技能拥有者的头像，但是考虑到其他角色额外获得的技能，会和自身额外的技能一样不易区分。所以定为现在这个样子。

**Comment by BeginnerSlob** [comment]
@Fsu0413 @YanGuam @takashiro @ainomelody 
来说说观点

**Comment by YanGuam** [comment]
3其他角色技能在右侧显示头像。

**Comment by BeginnerSlob** [comment]
你这样还是不能区分其他角色获得的技能和自己额外获得的技能，因为都是黑的

**Comment by YanGuam** [comment]
其实可以做个特别的icon代替头像

**Comment by BeginnerSlob** [comment]
他们有提议画一个，就是同时出现主将副将，副将放在右下角，主将放在左上角，size相同，重叠部分面积为单个头像的四分之一，重叠部分主将在上。

**Comment by Fsu0413** [comment]
英姿英魂在孙策获得的时候，是特定角色相关，所以以我的想法是加上孙策的头像比较好。
勇决是角色无关，但是和糜夫人的技能相关，所以我的建议是加上糜夫人的头像。

至于其他的技能，比如发动其他人的技能，放上其他人的头像。
原因未知的附加技能（比如作弊代码handleAcquireDetachSkills），加上自己的头像。
双将的情况，主副将都显示，左右各一半。

**Comment by BeginnerSlob** [comment]
之前他们和我谈的时候我也是这么回答的，然后他们问我董卓获得崩坏然后被断肠怎么办？
明明是个白板董卓，看起来还有崩坏，我仔细的想了想确实不太好。

**Comment by YanGuam** [comment]
支持虫妹。 不过有够小的。。

**Comment by Fsu0413** [comment]
董卓获得崩坏然后断肠，确实还有崩坏，不过因为角色相关还是画上董卓的头像更好些吧……

**Comment by BeginnerSlob** [comment]
@YanGuam 关于如何同时显示双将的问题还有待确定- -毕竟位置就这么点。。比如并排显示两个？

**Comment by Fsu0413** [comment]
进度怎样

**Comment by YanGuam** [comment]
我再想想

**Comment by Fsu0413** [comment]
不行就关，等新架构再做，反正这个已经确定要放弃了

**Comment by YanGuam** [comment]
转移到新架构吧，触发顺序的分类也是。= =
现在特别厌恶用C++写UI。
