### ISSUE TITLE
飞龙夺凤杀死角色后变身不能

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#29]
询问是否变身时双方同意后，被杀死角色若原本不是蜀国，则无法选择蜀国角色（可能与askForGeneral中的同国机制有关）
PS：似乎用changeHero有些不妥？

**Comment by BeginnerSlob** [comment]
askForGeneral的部分我修了，但是changeHero似乎不妥？

**Comment by Fsu0413** [comment]
不用changeHero的话，我实在不知道应该用什么

**Comment by YanGuam** [comment]
额外设置一下势力

**Comment by Fsu0413** [comment]
势力设置了啊

**Comment by BeginnerSlob** [comment]
= =主要问题是技能。。

**Comment by Fsu0413** [comment]
changeHero后技能无效我也发现了……但是我还不知道技能无效的原因…………

**Comment by BeginnerSlob** [comment]
现在UI上已经正常了（除了主将技能按钮在副将上）
除此以外，玩家拥有技能还是原有技能，新技能只存在于UI上

**Comment by YanGuam** [comment]
accepted.   ——司马氏老中医  专治疑难杂症三十年

**Comment by YanGuam** [comment]
fixed. 52bd2b3556385a0516fee11c7375856c6c32d00b
