### ISSUE TITLE
Room::doDragonPhoenix的一点问题

### ISSUE THREAD

**Issue by xusine** [Mogara/QSanguosha-For-Hegemony#297]
这个函数是为了简化飞龙而设计的。
现在的问题是亮将不正确，比如说使用副将的技能会亮出主将。
有时候主将会获得武将上明确标明的副将技。
暂时的问题就这些，说不好有其他的小问题。

**Comment by Fsu0413** [comment]
大至急求修复
飞龙目前问题超多，包括飞龙摸上来的一张牌都会被弃掉。
棺材的Lua目前还有闪退问题，周日一起解决。

周日Release因此取消，周一再Release。

**Comment by Fsu0413** [comment]
【老A闲着没事不呱】【皮卡丘】Fsu0413fsu0413@mogara.org 2015-05-24 0:23:00
飞龙本身崩不崩
怪蜀黍RuGaL(35152531) 2015-05-24 0:38:18查看前后消息
飞龙夺凤正常
【老A闲着没事不呱】【皮卡丘】Fsu0413fsu0413@mogara.org 2015-05-24 0:42:44
飞龙没问题那就先发了再说，那个函数到时候再修，发1.2.1
怪蜀黍RuGaL(35152531) 2015-05-24 1:44:44
@【老A闲着没事 
飞龙夺凤虽然没崩，但还是有问题的
死亡奖励还是正常结算，复活后摸的那一张牌也被弃掉

**Comment by Fsu0413** [comment]
@Xusine1131 这个没问题就关了吧
