### ISSUE TITLE
新一轮的AI汇总

### ISSUE THREAD

**Issue by xusine** [Mogara/QSanguosha-For-Hegemony#298]
大部分问题都转自贴吧反馈贴，适用于1.2.0
由于鄙人在AI方面并没有太大的研究，所以希望大家一起来解决。
@zyun7799 正切有时间的话帮忙处理一下。
1.国战无懈可击问题，对应反馈贴的13楼，同时火诸葛手憋无懈可击的问题。
2.黄盖自杀的决心很大了，计算用曹丕依然死的深沉，对应反馈贴问题14楼。
3.荀彧盲目驱虎，对应反馈贴15楼。
4.夏侯渊、陆逊盲目神速和以逸待劳，大概需要限制一下，对应反馈贴18楼。
5.远交近攻的目标不得当，对应反馈贴19楼。
6.大乔流离和自己绑在一起的玩家……对应反馈贴20楼。
7.暗将不能意识到自己即将成为野心家……这个难度看似比较大，对应反馈贴26楼。

**Comment by Fsu0413** [comment]
新框架再说
