### ISSUE TITLE
叠置

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-For-Hegemony#30]
![6 7 755 kzgu rhfb](https://f.cloud.github.com/assets/4150545/2086780/d6ad5ae0-8e5e-11e3-9962-4a2b13f00cd8.jpg)

**Comment by hejun442001** [comment]
其实我有个建议，不过工程浩大：
叠置是用画中画显示。

**Comment by YanGuam** [comment]
@hejun442001   嗯哼？   具体是什么样的呢

**Comment by YanGuam** [comment]
accepted.

**Comment by YanGuam** [comment]
ok   未来改成两个武将图相叠加。

**Comment by hejun442001** [comment]
@YanGuam ： 具体是什么样的呢？
叠置就像神杀老板（v1版）的效果：副将在圆环中的那个。
平置就就用现在的。
问题是主视角的头像咋处理？

**Comment by YanGuam** [comment]
不太好处理

**Comment by BeginnerSlob** [comment]
还是改成主副将相互叠加吧。。。
