### ISSUE TITLE
Error when build complete

### ISSUE THREAD

**Issue by Alehap** [Mogara/QSanguosha-For-Hegemony#304]
Hello,
Please help me to fix this error
![23-07-2015 8-41-22 ch](https://cloud.githubusercontent.com/assets/7158050/8851692/4faf7624-317b-11e5-8c75-662c26211ef4.png)

I'm using Qt 5.4.2 with swig 3.0.6

Thank you too much

**Comment by xusine** [comment]
It seems that you don't run the linguist before to generate translaton files.
But this doesn't matter. You can find the game in Bin folder.

**Comment by Alehap** [comment]
Thank you so much!
