### ISSUE TITLE
vld_x86 missing

### ISSUE THREAD

**Issue by Alehap** [Mogara/QSanguosha-For-Hegemony#305]
Hello,
I've got this error after successful build.
![26-07-2015 12-23-07 sa](https://cloud.githubusercontent.com/assets/7158050/8890489/ec40cecc-332c-11e5-8d8e-3bd572663195.png)
When I coppied it from vld_essentials\win32 this error show up
![26-07-2015 12-26-27 sa](https://cloud.githubusercontent.com/assets/7158050/8890496/0614af44-332d-11e5-8bae-b621f62d232e.png)

Please help me to fix this problem, thank you too much!!

**Comment by Alehap** [comment]
BTW, how I can build with release mode (use Qt5Core.dll instead of Qt5Cored.dll)
Thank you too much!

**Comment by Fsu0413** [comment]
debug mode is broken. use the release mode so that the program can run properly.
