### ISSUE TITLE
How to add new hero-skin

### ISSUE THREAD

**Issue by Alehap** [Mogara/QSanguosha-For-Hegemony#309]
Hello,
I've tried to add new general's skin in hero-skin folder.
I've created a subfolder named "caiwenji", and it has 2 more sub folder with named "1" and "2" (skinid) for two skins.
In each skinid folder, I've put 3 files avatar.png, card.jpg and full.png like the sample.

When I'm playing game, I can see the hero-skin-change-icon, I can click to new skin which I've added.
But then, My QSanguosha had force-closed.

Please help me to add a new hero-skin, thank you too much.

**Comment by xusine** [comment]
Do you add the lua translation file like zh_CN.lua ?

**Comment by Alehap** [comment]
Hello Xusine,
I don't add any lua translation files, only 3 files like avatar.png, card.jpg and full.png.
Do I missed it?

Thank you.

**Comment by xusine** [comment]
@Alehap 
I think you should.  Refer to the example and try to add one.（Maybe it's difficult for you to understand the Chinses :) ）

**Comment by Alehap** [comment]
Thank you @Xusine1131, I'll try this solution.
BTW how can I modify the general's skill like the sanguosha.com and is it possible to merge QSanguosha V2 and this project?
Thank you too much^^

**Comment by xusine** [comment]
@Alehap You'd better not pay too much attention to DIY in Hegemony.
The Hegemony‘s Skill API is totally different from that of V2. 
At the same time, Mogara is trying to merge the V2 and Hegemony by creating a new framework. 
https://github.com/Mogara/QSanguosha-New-Framework 
If you're interested in new framework and want to develop it, you can just join Mogara.
@sunnylife He is our master now, you can get more details from him.

**Comment by Alehap** [comment]
Oh thank you too much @Xusine1131  ^^

**Comment by xusine** [comment]
@Alehap 
Do you use QQ International ? If so, we can communicate with each other more conveniently.

**Comment by Alehap** [comment]
@Xusine1131 Sorry, I'm not use QQ, but I've a Skype account.
My developer skill isnot good, so I afraid that I cannot help you to develope this project :(

**Comment by Fsu0413** [comment]
@alehap Do you have a WeChat account? Since Skype is hardly used in Chinese.

**Comment by Alehap** [comment]
Hello @Fsu0413 , I don't have any Chinese Account.
But I'll try to register a QQ account soon.
Then I'll repost my QQ account in here.

**Comment by Alehap** [comment]
Hello
My QQ number is: 1219059541

**Comment by MagicPro1994** [comment]
I wonder why we need to change the skin of the heroes in Guozhan Mode...

**Comment by Fsu0413** [comment]
because OL does so.
