### ISSUE TITLE
清理无用代码与资源

### ISSUE THREAD

**Issue by YanGuam** [Mogara/QSanguosha-For-Hegemony#32]
核心组件开发进入尾声，可以精简一下了

**Comment by Fsu0413** [comment]
资源已经精简的差不多了，图片我不知道怎么弄的，配音是我移动走之后一个一个对照技能表移动回来的，没用的都删了

**Comment by Fsu0413** [comment]
server.cpp里无用的选项都删掉了

**Comment by Fsu0413** [comment]
旧的Scenario已经被干掉，GuhuoDialog被干掉
