### ISSUE TITLE
投降有bug，目前按照身份局结算的

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-For-Hegemony#35]
暂时不处理这个问题，有些人认为留着这个bug的投降很好的
我晕………………

**Comment by omnisreen** [comment]
还是走平局好= =

------------------ 原始邮件 ------------------
发件人: "Fsu0413"; 
发送时间: 2014年2月6日(星期四) 晚上7:35
收件人: "Fsu0413/QSanguosha-For-Hegemony"; 
主题: [QSanguosha-For-Hegemony] 投降有bug，目前按照身份局结算的 (#35)

暂时不处理这个问题，有些人认为留着这个bug的投降很好的
 我晕………………

&mdash;

**Comment by Fsu0413** [comment]
@omnisreen 我也感觉走平局好………………

**Comment by YanGuam** [comment]
平局吧- -

**Comment by Fsu0413** [comment]
突然发现修改Room::makeSurrender()函数会影响单机……wontfix
