### ISSUE TITLE
读条的问题，据说OL就算预亮了，读条也是全场的。。

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#38]
。。不预亮就不读条，预亮了就读全场条。。。。
PS:有新ISSUE了，而且不好修啊。。

**Comment by YanGuam** [comment]
未亮将的cost询问 进行全场读条 如何？

**Comment by Fsu0413** [comment]
只要对未亮将的询问，除了activate之外，都是全场读条，怎样

**Comment by BeginnerSlob** [comment]
@Fsu0413 不可行，因为还有askForChoice之类的，啦啦思路可行= =

**Comment by BeginnerSlob** [comment]
fixed
