### ISSUE TITLE
我这边ai选将陆逊+周泰

### ISSUE THREAD

**Issue by hejun442001** [Mogara/QSanguosha-For-Hegemony#45]
![qq20140211193405](https://f.cloud.github.com/assets/975086/2136356/7d1d5032-9310-11e3-90af-ff590c16074b.png)
10人局~
log稍后~

**Comment by BeginnerSlob** [comment]
= =？什么问题？

**Comment by hejun442001** [comment]
对不起  一直以为周泰是蜀将   我晕~
