### ISSUE TITLE
贴吧反馈0.5.1版本bug记录列表

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-For-Hegemony#48]
ai：
- [x] 1.AI 马腾 甘夫人 祝融不发动技能
- [ ] 2.黄盖手里有连弩，杀不到人会盲目自杀

程序本身：
- [ ] 1.有时程序会突然跑满一个核的cpu
- [ ] 2.changehero不加limitmark
- [x] 3.偶尔的南蛮卡死（目测君张角引起的）
- [x] 4.回放录像闪退
- [x] 5.突袭恂恂同时发动，涅槃激诏同时发动
- [x] 6.张辽容易引起卡牌

**Comment by YanGuam** [comment]
解决的打勾划掉

**Comment by BeginnerSlob** [comment]
第五条我是特意设置的- -，如果不要飞龙把卡牌包关掉就好了。。。我关了。

**Comment by BeginnerSlob** [comment]
第九条我目前为止遇到了两次，似乎是存档概率性损坏。

**Comment by Fsu0413** [comment]
取消崩溃在gui上，目测是CardsMoveStruct传输错误

补充……不在gui上，在服务器里……服务器把move.from传错了……

**Comment by BeginnerSlob** [comment]
第2条除了断粮好像都解决了 - -GG
