### ISSUE TITLE
cost里askForUseCard的技能要开发新接口

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-For-Hegemony#49]
避免突袭恂恂同时发动问题

**Comment by Fsu0413** [comment]
![qq20140215204602](https://f.cloud.github.com/assets/4150545/2177831/2a6bc864-963f-11e3-8d14-e7dee1a3fd94.png)

**Comment by BeginnerSlob** [comment]
= =所以说一次执行所有消耗是不合理的= =但是这两个技能一起发动是合理的吧= =

**Comment by Fsu0413** [comment]
这两个技能都是放弃摸牌为消耗，所以只能发动一个

**Comment by BeginnerSlob** [comment]
我选的执行一个cost紧接着执行一个effect比较合理，我决定动手改了，@Fsu0413 @YanGuam 可行么？

**Comment by Fsu0413** [comment]
cost是技能消耗，按照插入结算原则，肯定是倒序结算的

**Comment by BeginnerSlob** [comment]
但是没有任何规定说明必须所有同时机技能执行完消耗以后，才依次结算效果啊

**Comment by Fsu0413** [comment]
暂时用了个很囧的方法解决了这个问题，不用开新接口了
