### ISSUE TITLE
离间无法选择本应该可以选择的目标

### ISSUE THREAD

**Issue by BeginnerSlob** [Mogara/QSanguosha-For-Hegemony#50]
无法重现。

**Comment by Fsu0413** [comment]
![qq20140129223413](https://f.cloud.github.com/assets/4150545/2178429/30254cee-9667-11e3-8eeb-fe5fb9dc54b7.png)
如果两周之后没有bug报告这件事就close

**Comment by Fsu0413** [comment]
没收到反馈，close，等不及了

**Comment by Fsu0413** [comment]
知道问题所在了……fixed
