### ISSUE TITLE
现在版本的界面有点小问题

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-For-Hegemony#51]
估计是界面update之后导致QSS失效
暂时把最近一次界面改动revert了，开了个新branch放原来的代码

**Comment by Fsu0413** [comment]
![qq20140219125133](https://f.cloud.github.com/assets/4150545/2203510/9a7ad836-9921-11e3-8b24-3a362004b4b8.png)

**Comment by YanGuam** [comment]
fixed. 3f28ec0f57540ffc6cbc143739f5e36888cfbcec
