### ISSUE TITLE
Mac下服务器客户端不同步，没法玩

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-For-Hegemony#57]
具体表现为客户端发的东西服务器收不到

**Comment by Fsu0413** [comment]
不对……是服务器发的东西客户端收不到，用mac做服务器，Windows连接上可以正常玩，Windows做服务器的话mac连接会丢包

**Comment by YanGuam** [comment]
新成员的平台是OSX...        可以等他加入后把OSX的部分交给他负责

**Comment by Fsu0413** [comment]
@YanGuam 在高城改完JsonValue之后再试试看看还有没有这情况…………

**Comment by Fsu0413** [comment]
我怎么感觉是更新手牌数的那个东西的问题……我哪天试试换种实现方法

**Comment by Fsu0413** [comment]
……Mac虚拟机被我删了

**Comment by Fsu0413** [comment]
不知为何居然好了……………………不明觉厉

**Comment by BeginnerSlob** [comment]
= =太虎了。

**Comment by Fsu0413** [comment]
@BeginnerSlob 谁知道了………………
