### ISSUE TITLE
属性伤害AI

### ISSUE THREAD

**Issue by YanGuam** [Mogara/QSanguosha-For-Hegemony#63]
只要连子连着自己人跟敌人，不管自己人多还是敌人多，哪怕对自己很不利，AI也要属性伤害去搞自己或自己人。
![](http://imgsrc.baidu.com/forum/w%3D580/sign=32ae418a9b25bc312b5d01906ede8de7/ae015b2c11dfa9ec9548c25360d0f703908fc166.jpg)
By 河大第三任校长![](http://tb.himg.baidu.com/sys/portrait/item/f96ebad3b4f3b5dac8fdc8ced0a3b3a4d427)

**Comment by YanGuam** [comment]
@QSanguosha-Rara/ai-team

**Comment by YanGuam** [comment]
![](http://imgsrc.baidu.com/forum/w%3D580/sign=e55dcbba39c79f3d8fe1e4388aa0cdbc/0dddd5f9d72a6059094d6f5f2a34349b023bba6c.jpg)
AI自杀把能赢的牌打输了，敢再2B点么，三人连，都一血，还火杀

By uplink_wkj

**Comment by YanGuam** [comment]
10人局
蒋钦/董袭&陈武
我把自己和下下家的贾诩/纪灵连起来了，我下家丁奉/香香用火杀杀贾诩和我

想用属性和铁索造成两次伤害的想法是不错，但是得看位置啊，这样一来差点让我掉了两血，望修复这AI。(无截图，有记录，看不了)

By 开国大佬

**Comment by ainomelody** [comment]
铁索上就绑了2个吴国，第三个吴国毅然出了火杀
![image](https://cloud.githubusercontent.com/assets/7959436/3658759/63615966-11a7-11e4-9e10-8429b5f1a466.png)

by 魔の某只娃

**Comment by lrl026** [comment]
@e9ae21acd52cbe2bc9934bcd8718cc851ac805a5

应该不是属性伤害判断问题，有可能是身份判断的问题

**Comment by ainomelody** [comment]
姜维/诸葛亮 使用了 酒[9]
姜维/诸葛亮 使用了 雷杀[8]，目标是 暗将/华佗
姜维/诸葛亮 使用【酒】，对 暗将/华佗 造成的伤害从 1 点增加至 2 点
姜维/诸葛亮 对 暗将/华佗 造成了 2 点伤害[雷电属性]
暗将/华佗 当前体力为 -1 ，体力上限为 3
暗将/华佗 向 姜维/诸葛亮, 暗将/华佗, 臧霸/张辽, 孙坚/太史慈, 陈武＆董袭/徐盛, 暗将/于吉 求桃，一共需要 2 张【桃】
潘凤/华佗 明置了武将，主将为 潘凤，副将为 华佗
潘凤/华佗【群】 阵亡，伤害来源为 姜维/诸葛亮
杀[J] 被置入弃牌堆
乐不思蜀[6] 被置入弃牌堆
姜维/诸葛亮 摸了 2 张牌
姜维/诸葛亮 处于横置状态，将受到传导的属性伤害
姜维/诸葛亮 对 姜维/诸葛亮 造成了 2 点伤害[雷电属性]
姜维/诸葛亮 当前体力为 -1 ，体力上限为 3
姜维/诸葛亮 向 姜维/诸葛亮, 臧霸/张辽, 孙坚/太史慈, 陈武＆董袭/徐盛, 暗将/于吉 求桃，一共需要 2 张【桃】
姜维/诸葛亮【蜀】 自杀

0.6.0
by chh317

**Comment by lrl026** [comment]
大部分都是身份判断错误造成的
