### ISSUE TITLE
AI身份判断

### ISSUE THREAD

**Issue by YanGuam** [Mogara/QSanguosha-For-Hegemony#66]
常常看到明将AI把暗将打死(未使用知己知彼且暗将未跳势力)，结果翻开是同国的悲剧...这是正常的思路吗...?另外，AI现在似乎不会看大势? 

By abc36952000 ![](http://tb.himg.baidu.com/sys/portrait/item/a8146162633336393532303030e33e)

@QSanguosha-Rara/ai-team

**Comment by lrl026** [comment]
只有随到2b的ai才会打死完全未明身份的暗将

**Comment by YanGuam** [comment]
为何设置这种水平的ai= =

**Comment by lzxqqqqq** [comment]
这个错误出在友军判定上。因为友军我写了除非能顺带带走一个敌人否则绝对不会杀的。

**Comment by lrl026** [comment]
@e9ae21acd52cbe2bc9934bcd8718cc851ac805a5
