### ISSUE TITLE
枭姬AI

### ISSUE THREAD

**Issue by YanGuam** [Mogara/QSanguosha-For-Hegemony#67]
孙尚香枭姬AI，不知道是不是个例。
![](http://imgsrc.baidu.com/forum/w%3D580/sign=4f8dc3b1b54543a9f51bfac42e168a7b/cc3d7ac6a7efce1b6182d58fad51f3deb58f6518.jpg)

回复 Fsu0413 :我的意思是这时候他应该选择只弃一张装备，这样才是正常的打法。不浪费一张装备。。。 

By [李高123456789](http://tieba.baidu.com/home/main?un=%C0%EE%B8%DF123456789&fr=pb) ![](http://tb.himg.baidu.com/sys/portrait/item/deadc0eeb8df313233343536373839240c)

@QSanguosha-Rara/ai-team

**Comment by Fsu0413** [comment]
solved

**Comment by ainomelody** [comment]
醉了- -

**Comment by ainomelody** [comment]
![image](https://cloud.githubusercontent.com/assets/7959436/5181963/c7e464c2-74d6-11e4-87a4-2dc214d4f194.png)

**Comment by lrl026** [comment]
手牌更有价值
