### ISSUE TITLE
诸葛连弩AI

### ISSUE THREAD

**Issue by YanGuam** [Mogara/QSanguosha-For-Hegemony#70]
关羽装麒麟弓，手牌有连弩，先装连弩再开杀，我觉得是我的话，会先用麒麟弓杀，然后再装连弩继续杀
![](http://imgsrc.baidu.com/forum/w%3D580/sign=4e758527fa1986184147ef8c7aec2e69/bc2c9525bc315c60c9c66ba98fb1cb1348547773.jpg)

By mfdsrax2

@QSanguosha-Rara/ai-team

**Comment by lrl026** [comment]
5c1183c11ea70d8b4b4d91ab4cf66ec0a9cc5486
