### ISSUE TITLE
飞龙夺凤AI

### ISSUE THREAD

**Issue by YanGuam** [Mogara/QSanguosha-For-Hegemony#71]
用飞龙杀AI，AI弃牌似乎不会弃装备，比如曹洪张辽装青钢，手牌闪，他宁愿弃闪也不弃青钢，最终死亡
![](http://imgsrc.baidu.com/forum/w%3D580/sign=a47b43e15bee3d6d22c687c373176d41/6715933df8dcd1004fe7a867708b4710b8122f4b.jpg)

By mfdsrax2

@QSanguosha-Rara/ai-team

**Comment by lrl026** [comment]
记得很早就改过了，简单测了下木有问题，关了
