### ISSUE TITLE
Linux下现在游戏卡死在MainWindow，有时可以载入StartScene，但是按钮点击不能

### ISSUE THREAD

**Issue by Fsu0413** [Mogara/QSanguosha-For-Hegemony#78]
rt

**Comment by Fsu0413** [comment]
目测坑爹SSL问题，有的Windows机器因为安装了和Qt不兼容的OpenSSL导致游戏刚刚打开就崩溃退出

**Comment by Fsu0413** [comment]
想去论坛申请大约3K的空间来放更新信息，删掉Github上这些更新信息，SSL连接太坑

**Comment by YanGuam** [comment]
论坛三天崩一次    不太可靠...

**Comment by Fsu0413** [comment]
总比ssl强

**Comment by Fsu0413** [comment]
问题根源找到，UpdateCheckerThread中：
QNetworkReply *reply = mgr->get(QNetworkRequest(QUrl(URL)));
这句会在控制台输出一个错误

**Comment by YanGuam** [comment]
什么错误

**Comment by Fsu0413** [comment]
![a](https://cloud.githubusercontent.com/assets/4150545/3139419/2fadd06a-e8dd-11e3-9957-8fde78b9bb80.jpg)

这个消息出来之后窗口出来就卡死，然后就只能杀进程

**Comment by Fsu0413** [comment]
这个Ubuntu里的Qt版本为4.8.5

**Comment by Fsu0413** [comment]
已经解决，进程不能在自身执行时terminate
