### ISSUE TITLE
AI崩坏了~只会弃牌过了~

### ISSUE THREAD

**Issue by hejun442001** [Mogara/QSanguosha-For-Hegemony#8]
AI代码要整理了~

**Comment by hejun442001** [comment]
举出几个问题
1：
lua/ai/smart-ai.lua:4288: attempt to call method 'getGuhuoCard' (a nil value)
activate
stack traceback:
    lua/ai/smart-ai.lua:166: in function <lua/ai/smart-ai.lua:146>
2：
lua/ai/standard-ai.lua:492: attempt to call method 'needBear' (a nil value)
askForSkillInvoke
stack traceback:
    lua/ai/smart-ai.lua:166: in function <lua/ai/smart-ai.lua:146>
3：
ua/ai/standard_cards-ai.lua:52: attempt to call method 'cantbeHurt' (a nil value)
filterEvent
stack traceback:
    lua/ai/smart-ai.lua:166: in function <lua/ai/smart-ai.lua:146>
4：
ua/ai/smart-ai.lua:4288: attempt to call method 'getGuhuoCard' (a nil value)
askForDiscard
stack traceback:
    lua/ai/smart-ai.lua:166: in function <lua/ai/smart-ai.lua:146>
lua/ai/smart-ai.lua:2867: attempt to call method 'needDeath' (a nil value)
5：
lua/ai/maneuvering-ai.lua:73: assertion failed!
activate
stack traceback:
    lua/ai/smart-ai.lua:166: in function <lua/ai/smart-ai.lua:146>

**Comment by Fsu0413** [comment]
着什么急……

**Comment by Fsu0413** [comment]
等技能写完了bug处理的差不多了就该到AI了

**Comment by YanGuam** [comment]
AI修复已启动
