### ISSUE TITLE
Compile on Win7x64 with vs2013 qt5 failed?

### ISSUE THREAD

**Issue by stlyx** [Mogara/QSanguosha-For-Hegemony#83]
Qt5Core.lib(Qt5Core.dll) : fatal error LNK1112: 模块计算机类型“x64”与目标计算机类型“X86”冲突

**Comment by Fsu0413** [comment]
使用X64的Qt库

**Comment by Fsu0413** [comment]
切换解决方案平台为X64

**Comment by stlyx** [comment]
谢@Fsu0413 ，终于编译成功了。但是只能在vs2013里面通过调试启动？不能直接双击.exe运行？（双击.exe时解决了dll缺失问题仍然不能运行.exe，提示“
应用程序无法正常启动(0xc000007b)，请单击“确定”关闭应用程序。
”，这是何解？）

**Comment by YanGuam** [comment]
@stlyx    运行库不在exe的同级目录中。
