### ISSUE TITLE
飞龙夺凤后势力判断AI

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#85]
八人局 吴国周瑜/陆逊被群的飞龙夺凤之后变成了吕布/士兵，吴大师/陈董被飞龙夺凤成了袁绍士兵，某回合开始，吕布居然对袁绍出杀，这回合结束二张/丁奉还让吕布回收了弃牌（此时场上有四个群两个吴一个蜀，应该不存在暂时结盟的问题）
![image](https://cloud.githubusercontent.com/assets/7959436/3508643/3052bc3c-068e-11e4-84d5-e0524f4f6f42.png)

BY 快棋手

**Comment by Fsu0413** [comment]
问问他是不是用的旧版

**Comment by ainomelody** [comment]
0.5.1的BUG，无法重现，若已修复，close please

**Comment by ainomelody** [comment]
接楼上那局 袁绍当万箭 董卓帮蜀国出国无懈却不帮群雄无懈（董卓本身就是群雄，不是被飞龙夺凤的）
![image](https://cloud.githubusercontent.com/assets/7959436/3564439/69ea7840-0a85-11e4-977f-165f9fd6c734.png)

**Comment by Fsu0413** [comment]
国无懈的使用没有特别写AI

**Comment by lrl026** [comment]
试过几盘飞龙夺凤后势力判断应该没有问题了
