### ISSUE TITLE
莫名弃牌

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#90]
刚开始，一摸牌莫名叫我弃牌
![image](https://cloud.githubusercontent.com/assets/7959436/3564504/c8d3116a-0a89-11e4-8b93-ba41be4483f9.png)
游戏中我被闪电劈了，然后这回合就结束了……不能出牌直接叫我弃置
![image](https://cloud.githubusercontent.com/assets/7959436/3564505/d4537c96-0a89-11e4-98fc-7bb0539ccea6.png)
by 俺是张学友

**Comment by Fsu0413** [comment]
电脑空格键卡住，不是程序问题，close。

**Comment by YanGuam** [comment]
戳中笑点...2333

**Comment by BeginnerSlob** [comment]
真的笑了。。。哈哈哈
