### ISSUE TITLE
鬼才改判铁骑AI

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#94]
马超杀司马判红，司马手牌没闪仍然改黑
![image](https://cloud.githubusercontent.com/assets/7959436/3564672/1825a49a-0a93-11e4-9097-3bb9d0df852f.png)
0.5.1
by mfdsrax2

**Comment by Fsu0413** [comment]
AI只判断judge.pattern和judge.good，不判断实际情况导致

**Comment by lrl026** [comment]
@bee051c83a8b588c69625e8527db1a5c2511d6ae
