### ISSUE TITLE
双雄AI

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#95]
纪灵/颜文 有一把牌，双雄后发动双刃，没拼赢全弃了
我觉得颜文的AI还是有问题，之前也发现经常双雄后不决斗，把决斗牌当装备装或者直接弃了
![image](https://cloud.githubusercontent.com/assets/7959436/3564695/1f0ef7ba-0a94-11e4-9507-558b16b5d220.png)
0.5.1
by mfdsrax2

**Comment by Fsu0413** [comment]
不知为何双雄AI总是要把决斗放到杀的后面出

**Comment by Fsu0413** [comment]
fixed by @zyun7799
