### ISSUE TITLE
二张固政卡牌

### ISSUE THREAD

**Issue by ainomelody** [Mogara/QSanguosha-For-Hegemony#99]
八人局，二张固政八卦后八卦还在手上，还可以给自己装，然后就闪退了
0.5.1
by 如释帆飞

**Comment by BeginnerSlob** [comment]
我觉得他想说的是直谏- -

**Comment by YanGuam** [comment]
我居然没看出来有问题= =

**Comment by ainomelody** [comment]
昨晚上梦游了0.0

**Comment by Fsu0413** [comment]
直谏爆过很多次问题了，不过就是不知道问题出在哪里

**Comment by ainomelody** [comment]
八人局
张昭/孙策
卡【闪】
敌对方弃置一牌，孙策/二张固政，还没反应过来，二张直谏自己，然后就开始卡【闪】崩溃
往回翻文字记录速度赶不上卡牌的速度，不知道具体触发条件。。
![image](https://cloud.githubusercontent.com/assets/7959436/3701999/cf666f3a-13f9-11e4-87fb-662b2bd0b354.png)
0.6.0
by 330de日子

**Comment by Fsu0413** [comment]
直谏卡牌是已知问题，但是不知道具体触发条件所以一直没有修。
如果他们可以提供记录的话会更好，光一张卡闪的图看不出来任何问题
